# Production rule: append new cards to the end of this list. Do not reorder existing
# entries, because import_alice_phrases derives stable deck keys from the current
# position, such as alice-0001, alice-0002, and so on.
ALICE_CARDS = [
    ('Alice moriva di noia.', 'Alice estava morrendo de tedio.', 'moriva di noia e uma expressao idiomatica: literalmente, morria de tedio.'),
    ('Se ne stava seduta con la sorella.', 'Ela estava sentada com a irma.', 'se ne stava indica permanecer em certo estado ou lugar.'),
    ('Non faceva niente.', 'Ela nao fazia nada.', 'non antes do verbo nega a acao; niente reforca a ideia de nada.'),
    ('Il libro non aveva figure.', 'O livro nao tinha figuras.', 'aveva e o imperfeito de avere, usado para descricoes no passado.'),
    ('Il libro non aveva dialoghi.', 'O livro nao tinha dialogos.', 'dialoghi mostra o plural de dialogo; o h mantem o som duro de g.'),
    ('A cosa serve un libro?', 'Para que serve um livro?', 'a cosa serve pergunta a utilidade de algo.'),
    ('Pensava Alice.', 'Alice pensava.', 'pensava e imperfeito: uma acao mental em andamento no passado.'),
    ('Faceva molto caldo.', 'Fazia muito calor.', 'faceva caldo e a forma natural para falar do clima.'),
    ('Alice si sentiva assonnata.', 'Alice se sentia sonolenta.', 'sentirsi e reflexivo; si sentiva significa ela se sentia.'),
    ('Voleva fare una collana di margherite.', 'Ela queria fazer um colar de margaridas.', 'voleva fare combina querer com infinitivo: queria fazer.'),
    ('All improvviso passo un coniglio bianco.', 'De repente passou um coelho branco.', 'all improvviso marca uma mudanca repentina na cena.'),
    ('Il coniglio aveva gli occhi rosa.', 'O coelho tinha olhos cor-de-rosa.', 'gli occhi usa gli antes de palavra masculina plural iniciada por vogal.'),
    ('Il Coniglio mormorava qualcosa.', 'O Coelho murmurava alguma coisa.', 'mormorava sugere fala baixa e continua no passado.'),
    ('Ohime! Faro tardi!', 'Ai de mim! Vou me atrasar!', 'faro e futuro de fare; aqui significa vou fazer/ficar tarde.'),
    ('Alice non si meraviglio troppo.', 'Alice nao ficou muito surpresa.', 'meravigliarsi e reflexivo: maravilhar-se ou surpreender-se.'),
    ('Tutto le parve naturale.', 'Tudo lhe pareceu natural.', 'le significa a ela; parve e passado remoto de parere.'),
    ('Il Coniglio tiro fuori un orologio.', 'O Coelho tirou um relogio.', 'tirare fuori significa tirar para fora.'),
    ('Lo guardo in fretta.', 'Ele o olhou rapidamente.', 'lo retoma orologio; in fretta quer dizer rapidamente.'),
    ('Poi corse via.', 'Depois saiu correndo.', 'correre via significa ir embora correndo.'),
    ('Alice balzo in piedi.', 'Alice deu um salto e ficou de pe.', 'balzare in piedi e levantar-se rapidamente.'),
    ('Le era venuta una grande curiosita.', 'Ela ficou com uma grande curiosidade.', 'le era venuta indica algo que veio a ela: surgiu nela.'),
    ('Corse attraverso il campo.', 'Ela correu pelo campo.', 'attraverso indica atravessar ou passar por um espaco.'),
    ('Il Coniglio entro nella tana.', 'O Coelho entrou na toca.', 'nella combina in + la; tana e toca.'),
    ('Alice gli corse dietro.', 'Alice correu atras dele.', 'gli aqui significa a ele; correre dietro e correr atras.'),
    ('Non penso a come sarebbe uscita.', 'Ela nao pensou em como sairia.', 'sarebbe uscita e condicional passado: teria saido.'),
    ('La tana andava dritta.', 'A toca seguia em linha reta.', 'andava descreve direcao; dritta significa reta.'),
    ('Poi scendeva all improvviso.', 'Depois descia de repente.', 'scendeva descreve movimento para baixo.'),
    ('Alice cadeva molto lentamente.', 'Alice caia muito lentamente.', 'lentamente e adverbio formado a partir de lento.'),
    ('Aveva tempo di guardarsi intorno.', 'Ela tinha tempo para olhar ao redor.', 'guardarsi intorno significa olhar ao redor.'),
    ('Vide scaffali e armadi.', 'Ela viu prateleiras e armarios.', 'vide e passado remoto de vedere, comum em narrativa literaria.'),
    ('Vide carte geografiche e quadri.', 'Ela viu mapas e quadros.', 'carte geografiche e o modo comum de dizer mapas.'),
    ('Prese un barattolo da uno scaffale.', 'Pegou um pote de uma prateleira.', 'prese e passado remoto de prendere.'),
    ('Sul barattolo c era scritto marmellata.', 'No pote estava escrito geleia.', 'sul combina su + il; c era significa havia/estava.'),
    ('Il barattolo era vuoto.', 'O pote estava vazio.', 'era e imperfeito de essere para descricao.'),
    ('Alice non volle lasciarlo cadere.', 'Alice nao quis deixa-lo cair.', 'lasciarlo junta lasciare + lo: deixar ele.'),
    ('Lo rimise in un armadio.', 'Ela o colocou de volta em um armario.', 'rimettere indica colocar novamente ou devolver ao lugar.'),
    ('Giu, giu, giu.', 'Para baixo, para baixo, para baixo.', 'giu indica direcao para baixo e cria ritmo narrativo.'),
    ('La caduta non finiva mai.', 'A queda nunca terminava.', 'non... mai corresponde a nunca.'),
    ('Alice comincio a parlare da sola.', 'Alice comecou a falar sozinha.', 'cominciare a + infinitivo significa comecar a fazer algo.'),
    ('Chissa quante miglia ho percorso.', 'Quem sabe quantas milhas eu percorri.', 'chissa expressa incerteza ou imaginacao.'),
    ('Forse attraversero tutta la terra.', 'Talvez eu atravesse a terra inteira.', 'forse introduz possibilidade; attraversero esta no futuro.'),
    ('Dina mi manchera molto.', 'Dina vai me fazer muita falta.', 'mi manchera segue a logica italiana: ela faltara para mim.'),
    ('Dina e la mia gatta.', 'Dina e a minha gata.', 'mia concorda com gatta, feminino singular.'),
    ('Spero che si ricordino del suo latte.', 'Espero que se lembrem do leite dela.', 'spero che costuma pedir subjuntivo: si ricordino.'),
    ('Finalmente Alice arrivo in fondo.', 'Finalmente Alice chegou ao fundo.', 'in fondo significa no fundo ou ao final.'),
    ('Atterro su un mucchio di foglie.', 'Ela pousou sobre um monte de folhas.', 'atterrare e pousar; su indica sobre.'),
    ('Non si fece male.', 'Ela nao se machucou.', 'farsi male significa machucar-se.'),
    ('Guardo in alto.', 'Ela olhou para cima.', 'in alto indica direcao para cima.'),
    ('Tutto era buio sopra di lei.', 'Tudo estava escuro acima dela.', 'sopra di lei significa acima dela.'),
    ('Davanti a lei c era un lungo passaggio.', 'Diante dela havia uma longa passagem.', 'davanti a lei marca posicao frontal.'),
    ('Il Coniglio correva ancora.', 'O Coelho ainda corria.', 'ancora aqui significa ainda.'),
    ('Alice parti come il vento.', 'Alice saiu como o vento.', 'come il vento e comparacao de velocidade.'),
    ('Lo senti dire: Sono in ritardo.', 'Ela o ouviu dizer: Estou atrasado.', 'sentire + infinitivo pode significar ouvir alguem fazer algo.'),
    ('Svolto l angolo in fretta.', 'Dobrou a esquina rapidamente.', 'svoltare l angolo e virar a esquina.'),
    ('Alice gli fu alle calcagna.', 'Alice ficou nos calcanhares dele.', 'essere alle calcagna significa estar muito perto atras.'),
    ('Si trovo in una sala lunga.', 'Ela se encontrou em uma sala longa.', 'trovarsi indica encontrar-se em um lugar.'),
    ('La sala era bassa e illuminata.', 'A sala era baixa e iluminada.', 'era descreve caracteristicas do ambiente.'),
    ('Lampade pendevano dal soffitto.', 'Lampadas pendiam do teto.', 'pendere dal soffitto significa pender do teto.'),
    ('C erano porte tutto intorno.', 'Havia portas por todos os lados.', 'tutto intorno quer dizer ao redor inteiro.'),
    ('Le porte erano tutte chiuse.', 'As portas estavam todas fechadas.', 'chiuse concorda com porte, feminino plural.'),
    ('Alice provo ad aprirle.', 'Alice tentou abri-las.', 'aprirle junta aprire + le, retomando as portas.'),
    ('Non riusci ad aprirne nessuna.', 'Nao conseguiu abrir nenhuma.', 'riuscire a indica conseguir; nessuna reforca nenhuma.'),
    ('Cammino triste nella sala.', 'Caminhou triste pela sala.', 'camminare descreve deslocamento a pe.'),
    ('Vide un tavolino di vetro.', 'Viu uma mesinha de vidro.', 'tavolino e diminutivo de tavolo.'),
    ('Sul tavolino c era una chiave.', 'Sobre a mesinha havia uma chave.', 'chiave e feminino em italiano: una chiave.'),
    ('La chiave era piccola e d oro.', 'A chave era pequena e de ouro.', 'd oro significa de ouro.'),
    ('Alice provo ogni porta.', 'Alice tentou cada porta.', 'ogni e singular mesmo com sentido de cada.'),
    ('La chiave non apriva niente.', 'A chave nao abria nada.', 'niente funciona como objeto negativo.'),
    ('Poi vide una porticina.', 'Depois viu uma portinha.', 'porticina e diminutivo de porta.'),
    ('La porticina era dietro una tenda.', 'A portinha estava atras de uma cortina.', 'dietro indica posicao posterior.'),
    ('La chiave entro nella serratura.', 'A chave entrou na fechadura.', 'serratura e fechadura.'),
    ('Alice apri la porticina.', 'Alice abriu a portinha.', 'apri e passado remoto de aprire.'),
    ('Dietro c era un piccolo passaggio.', 'Atras havia uma pequena passagem.', 'piccolo concorda com passaggio, masculino singular.'),
    ('Il passaggio era stretto.', 'A passagem era estreita.', 'stretto descreve algo apertado ou estreito.'),
    ('Alice si inginocchio.', 'Alice se ajoelhou.', 'inginocchiarsi e verbo reflexivo.'),
    ('Guardo attraverso il passaggio.', 'Olhou atraves da passagem.', 'attraverso pode ser preposicao: atraves de.'),
    ('Vide un giardino bellissimo.', 'Viu um jardim belissimo.', 'bellissimo e superlativo: muito bonito.'),
    ('Voleva entrare nel giardino.', 'Ela queria entrar no jardim.', 'entrare in vira entrare nel antes de il.'),
    ('Ma era troppo grande.', 'Mas era grande demais.', 'troppo antes de adjetivo significa demais.'),
    ('Non poteva passare.', 'Ela nao podia passar.', 'poteva e imperfeito de potere: podia.'),
    ('Torno al tavolino.', 'Voltou para a mesinha.', 'tornare a indica voltar para um lugar.'),
    ('Sperava di trovare un aiuto.', 'Esperava encontrar uma ajuda.', 'sperare di + infinitivo usa di.'),
    ('Trovo una bottiglietta.', 'Encontrou uma garrafinha.', 'bottiglietta e diminutivo de bottiglia.'),
    ('Sulla bottiglia c era un biglietto.', 'Na garrafa havia um bilhete.', 'biglietto pode ser bilhete ou etiqueta.'),
    ('Il biglietto diceva: bevimi.', 'O bilhete dizia: beba-me.', 'bevimi junta bevi + mi: beba-me.'),
    ('Alice lesse con attenzione.', 'Alice leu com atencao.', 'lesse e passado remoto de leggere.'),
    ('Controllo che non fosse veleno.', 'Verificou que nao fosse veneno.', 'veleno significa veneno; fosse e subjuntivo.'),
    ('Non c era scritto veleno.', 'Nao estava escrito veneno.', 'c era scritto e forma impessoal: estava escrito.'),
    ('Allora assaggio la bevanda.', 'Entao provou a bebida.', 'allora organiza a sequencia: entao.'),
    ('Aveva un sapore strano.', 'Tinha um sabor estranho.', 'sapore e sabor; strano e estranho.'),
    ('Sembrava torta di ciliegie.', 'Parecia torta de cerejas.', 'sembrava indica aparencia ou impressao.'),
    ('Sembrava crema e ananas.', 'Parecia creme e abacaxi.', 'sembrava se repete para listar sensacoes.'),
    ('Sembrava tacchino arrosto.', 'Parecia peru assado.', 'arrosto significa assado.'),
    ('Alice fini la bottiglietta.', 'Alice terminou a garrafinha.', 'finire pode significar terminar ou acabar.'),
    ('Che sensazione curiosa!', 'Que sensacao curiosa!', 'che antes de nome cria exclamacao.'),
    ('Sto diventando piccola.', 'Estou ficando pequena.', 'stare + gerundio indica acao em progresso.'),
    ('Divento alta solo venticinque centimetri.', 'Ficou com apenas vinte e cinco centimetros.', 'solo enfatiza apenas.'),
    ('Ora poteva passare dalla porta.', 'Agora podia passar pela porta.', 'ora significa agora.'),
    ('Ma aveva dimenticato la chiave.', 'Mas havia esquecido a chave.', 'dimenticare significa esquecer.'),
    ('La chiave era sul tavolino.', 'A chave estava sobre a mesinha.', 'sul tavolino retoma o local importante.'),
    ('Alice non poteva raggiungerla.', 'Alice nao podia alcanca-la.', 'raggiungerla junta raggiungere + la.'),
    ('Provo ad arrampicarsi.', 'Tentou escalar.', 'arrampicarsi e subir/escalar usando esforco.'),
    ('Scivolo di nuovo giu.', 'Escorregou de novo para baixo.', 'di nuovo significa de novo.'),
    ('Si sedette e pianse.', 'Sentou-se e chorou.', 'sedersi e reflexivo; si sedette e passado remoto.'),
    ('Basta piangere.', 'Chega de chorar.', 'basta + infinitivo expressa parar/chega de.'),
    ('Disse Alice a se stessa.', 'Disse Alice a si mesma.', 'a se stessa indica para si mesma.'),
    ('Poco dopo vide una scatola.', 'Pouco depois viu uma caixa.', 'poco dopo marca tempo: pouco depois.'),
    ('Dentro c era una torta.', 'Dentro havia um bolo.', 'dentro indica interior.'),
    ('Sulla torta era scritto: mangiami.', 'No bolo estava escrito: coma-me.', 'mangiami junta mangia + mi.'),
    ('Alice mangio un pezzetto.', 'Alice comeu um pedacinho.', 'pezzetto e diminutivo de pezzo.'),
    ('Aspetto qualche minuto.', 'Esperou alguns minutos.', 'qualche usa singular: qualche minuto.'),
    ('Non successe niente.', 'Nao aconteceu nada.', 'succedere significa acontecer.'),
    ('Allora mangio tutta la torta.', 'Entao comeu o bolo inteiro.', 'tutta concorda com torta, feminino singular.'),
    ('Alice crebbe rapidamente.', 'Alice cresceu rapidamente.', 'crescere vira crebbe no passado remoto.'),
    ('La testa tocco il soffitto.', 'A cabeca tocou o teto.', 'toccare significa tocar ou encostar.'),
    ('Prese subito la chiave.', 'Pegou imediatamente a chave.', 'subito significa imediatamente.'),
    ('Corse verso la porticina.', 'Correu em direcao a portinha.', 'verso indica direcao.'),
    ('Ora era troppo alta.', 'Agora estava alta demais.', 'troppo alta significa alta demais.'),
    ('Poteva solo guardare il giardino.', 'Podia apenas olhar o jardim.', 'solo pode significar apenas.'),
    ('Si mise a piangere di nuovo.', 'Comecou a chorar de novo.', 'mettersi a + infinitivo significa comecar a fazer.'),
    ('Le lacrime cadevano a terra.', 'As lagrimas caiam no chao.', 'lacrime e plural feminino.'),
    ('Si formo una grande pozza.', 'Formou-se uma grande poca.', 'formarsi indica formar-se.'),
    ('Alice si sgrido severamente.', 'Alice repreendeu a si mesma severamente.', 'sgridarsi e repreender-se.'),
    ('Non serve piangere cosi.', 'Nao adianta chorar assim.', 'servire aqui indica ter utilidade.'),
    ('Poco dopo senti dei passi.', 'Pouco depois ouviu passos.', 'sentire pode ser ouvir.'),
    ('Era il Coniglio Bianco.', 'Era o Coelho Branco.', 'era identifica quem apareceu.'),
    ('Portava guanti bianchi.', 'Usava luvas brancas.', 'portare pode significar usar/vestir acessorios.'),
    ('Portava anche un ventaglio.', 'Levava tambem um leque.', 'anche significa tambem.'),
    ('Sembrava molto preoccupato.', 'Parecia muito preocupado.', 'preoccupato e preocupado.'),
    ('Mormorava tra se.', 'Murmurava consigo mesmo.', 'tra se significa consigo mesmo.'),
    ('La Duchessa mi fara tagliare la testa.', 'A Duquesa mandara cortar minha cabeca.', 'mi fara + infinitivo indica fara comigo.'),
    ('Alice provo a parlargli.', 'Alice tentou falar com ele.', 'parlargli junta parlare + gli.'),
    ('Il Coniglio si spavento.', 'O Coelho se assustou.', 'spaventarsi e assustar-se.'),
    ('Lascio cadere guanti e ventaglio.', 'Deixou cair luvas e leque.', 'lasciare cadere significa deixar cair.'),
    ('Poi scappo nel buio.', 'Depois fugiu no escuro.', 'scappare e fugir.'),
    ('Alice raccolse il ventaglio.', 'Alice recolheu o leque.', 'raccogliere e pegar algo do chao.'),
    ('Faceva molto caldo nella sala.', 'Fazia muito calor na sala.', 'nella combina in + la.'),
    ('Si fece vento con il ventaglio.', 'Abanou-se com o leque.', 'farsi vento e abanar-se.'),
    ('Comincio a diventare piccola.', 'Comecou a ficar pequena.', 'diventare indica transformacao.'),
    ('Lascia cadere il ventaglio.', 'Deixa cair o leque.', 'o presente aqui deixa a acao viva e direta.'),
    ('Era quasi scomparsa.', 'Ela quase havia desaparecido.', 'quasi significa quase.'),
    ('Corse subito verso la porta.', 'Correu imediatamente para a porta.', 'verso mostra direcao para um alvo.'),
    ('La porta era ancora chiusa.', 'A porta ainda estava fechada.', 'ancora aqui significa ainda.'),
    ('La chiave era di nuovo sul tavolo.', 'A chave estava novamente sobre a mesa.', 'di nuovo significa novamente.'),
    ('Alice scivolo e cadde nell acqua.', 'Alice escorregou e caiu na agua.', 'cadere nell acqua: cair na agua.'),
    ('Era la pozza delle sue lacrime.', 'Era a poca das suas lagrimas.', 'sue concorda com lacrime.'),
    ('Ora nuotava nella pozza.', 'Agora nadava na poca.', 'nuotare e nadar.'),
    ('Vide un topo vicino a lei.', 'Viu um rato perto dela.', 'vicino a lei significa perto dela.'),
    ('Il topo nuotava bene.', 'O rato nadava bem.', 'bene e adverbio: bem.'),
    ('Alice parlo al topo.', 'Alice falou com o rato.', 'parlare a/con alguem: falar com alguem.'),
    ('Forse capisce il francese.', 'Talvez entenda frances.', 'forse expressa possibilidade.'),
    ('Il topo salto di paura.', 'O rato saltou de medo.', 'di paura indica causa: por medo.'),
    ('Alice chiese scusa.', 'Alice pediu desculpa.', 'chiedere scusa e pedir desculpa.'),
    ('Non voleva parlare di gatti.', 'Nao queria falar de gatos.', 'parlare di significa falar sobre.'),
    ('Il topo odiava i gatti.', 'O rato odiava gatos.', 'odiava e imperfeito de odiare.'),
    ('Arrivarono altri animali.', 'Chegaram outros animais.', 'arrivare usa essere nos tempos compostos, mas aqui e passato remoto.'),
    ('Tutti nuotavano nella pozza.', 'Todos nadavam na poca.', 'tutti indica todos.'),
    ('La riva era vicina.', 'A margem estava perto.', 'riva e margem.'),
    ('Uscirono dall acqua bagnati.', 'Sairam da agua molhados.', 'dall acqua combina da + l acqua.'),
    ('Erano tutti molto bagnati.', 'Todos estavam muito molhados.', 'bagnati concorda com tutti, masculino plural.'),
    ('Il topo sembrava arrabbiato.', 'O rato parecia irritado.', 'sembrava descreve aparencia ou impressao.'),
    ('Alice ascoltava con attenzione.', 'Alice escutava com atencao.', 'ascoltare e escutar de modo intencional.'),
    ('Il topo racconto una storia.', 'O rato contou uma historia.', 'raccontare significa contar uma historia.'),
    ('La storia era lunga e triste.', 'A historia era longa e triste.', 'lunga e triste concordam com storia.'),
    ('Alice penso alla coda del topo.', 'Alice pensou na cauda do rato.', 'coda pode significar cauda ou fila.'),
    ('Il topo si offese.', 'O rato se ofendeu.', 'offendersi e verbo reflexivo.'),
    ('Se ne ando in fretta.', 'Foi embora rapidamente.', 'andarsene significa ir embora.'),
    ('Alice rimase sola per un momento.', 'Alice ficou sozinha por um momento.', 'rimanere indica permanecer ou ficar.'),
    ('Gli animali volevano asciugarsi.', 'Os animais queriam se secar.', 'asciugarsi e secar-se.'),
    ('Il Dodo propose una corsa.', 'O Dodo propos uma corrida.', 'propose e passado remoto de proporre.'),
    ('Tutti cominciarono a correre.', 'Todos comecaram a correr.', 'cominciare a + infinitivo indica inicio de acao.'),
    ('Nessuno sapeva dove andare.', 'Ninguem sabia para onde ir.', 'nessuno significa ninguem.'),
    ('La corsa duro mezz ora.', 'A corrida durou meia hora.', 'durare indica duracao.'),
    ('Alla fine erano asciutti.', 'No fim estavam secos.', 'alla fine significa no fim.'),
    ('Il Dodo disse che tutti avevano vinto.', 'O Dodo disse que todos tinham vencido.', 'avevano vinto e mais-que-perfeito composto.'),
    ('Alice doveva dare i premi.', 'Alice devia dar os premios.', 'dovere no imperfeito indica obrigacao.'),
    ('Trovo dei confetti in tasca.', 'Encontrou confeitos no bolso.', 'in tasca significa no bolso.'),
    ('Diede un confetto a ciascuno.', 'Deu um confeito a cada um.', 'ciascuno significa cada um.'),
    ('Anche Alice ricevette un premio.', 'Alice tambem recebeu um premio.', 'anche significa tambem.'),
    ('Il premio era il suo ditale.', 'O premio era o seu dedal.', 'ditale significa dedal.'),
    ('Tutti applaudirono con serieta.', 'Todos aplaudiram com seriedade.', 'applaudire significa aplaudir.'),
    ('Alice parlo di nuovo di Dina.', 'Alice falou de novo de Dina.', 'di nuovo significa novamente.'),
    ('Gli animali ebbero paura.', 'Os animais tiveram medo.', 'avere paura significa ter medo.'),
    ('Uno dopo l altro andarono via.', 'Um depois do outro foram embora.', 'uno dopo l altro indica sequencia.'),
    ('Alice si senti molto sola.', 'Alice se sentiu muito sozinha.', 'sentirsi e reflexivo.'),
    ('Pianse ancora un poco.', 'Chorou ainda um pouco.', 'ancora un poco significa ainda um pouco.'),
    ('Poi senti dei passi piccoli.', 'Depois ouviu passos pequenos.', 'passi piccoli descreve passos pequenos.'),
    ('Il Coniglio tornava di corsa.', 'O Coelho voltava correndo.', 'tornare significa voltar.'),
    ('Cercava guanti e ventaglio.', 'Procurava luvas e leque.', 'cercare significa procurar.'),
    ('Alice si spavento e scappo.', 'Alice se assustou e fugiu.', 'spaventarsi e assustar-se.'),
    ('Il Coniglio la chiamo Mary Ann.', 'O Coelho a chamou de Mary Ann.', 'chiamare qualcuno indica chamar alguem.'),
    ('Le ordino di andare a casa.', 'Ordenou que ela fosse para casa.', 'ordinare di + infinitivo indica ordem.'),
    ('Alice obbedi senza discutere.', 'Alice obedeceu sem discutir.', 'senza + infinitivo significa sem fazer algo.'),
    ('Entro in una piccola casa.', 'Entrou em uma pequena casa.', 'entrare in indica entrar em lugar.'),
    ('Sali le scale in fretta.', 'Subiu as escadas rapidamente.', 'salire le scale e subir escadas.'),
    ('Trovo una stanza ordinata.', 'Encontrou um quarto arrumado.', 'ordinata significa arrumada ou organizada.'),
    ('Sul tavolo c era una bottiglia.', 'Sobre a mesa havia uma garrafa.', 'sul tavolo combina su + il.'),
    ('Alice bevve senza pensarci troppo.', 'Alice bebeu sem pensar muito nisso.', 'pensarci significa pensar nisso.'),
    ('Comincio a crescere subito.', 'Comecou a crescer imediatamente.', 'crescere indica aumento de tamanho.'),
    ('Il corpo riempi la stanza.', 'O corpo encheu o quarto.', 'riempire significa encher.'),
    ('Un braccio usci dalla finestra.', 'Um braco saiu pela janela.', 'uscire dalla finestra: sair pela janela.'),
    ('Un piede entro nel camino.', 'Um pe entrou na chamine.', 'camino significa lareira ou chamine.'),
    ('Alice non poteva muoversi.', 'Alice nao podia se mover.', 'muoversi e mover-se.'),
    ('Il Coniglio arrivo alla porta.', 'O Coelho chegou a porta.', 'arrivare a indica chegar a um lugar.'),
    ('Provo ad aprire la porta.', 'Tentou abrir a porta.', 'provare a + infinitivo significa tentar.'),
    ('La porta non si apriva.', 'A porta nao abria.', 'si apriva pode indicar abertura por si.'),
    ('Chiamo aiuto a gran voce.', 'Chamou ajuda em voz alta.', 'a gran voce significa em voz alta.'),
    ('Arrivo una lucertola di nome Bill.', 'Chegou um lagarto chamado Bill.', 'di nome introduz o nome de alguem.'),
    ('Bill sali sul tetto.', 'Bill subiu no telhado.', 'sul tetto significa sobre/no telhado.'),
    ('Alice senti rumori nel camino.', 'Alice ouviu barulhos na chamine.', 'rumori significa barulhos.'),
    ('Diede un calcio con il piede.', 'Deu um chute com o pe.', 'dare un calcio significa chutar.'),
    ('Bill volo fuori dal camino.', 'Bill voou para fora da chamine.', 'fuori da significa para fora de.'),
    ('I sassolini diventavano dolcetti.', 'As pedrinhas viravam docinhos.', 'diventare indica transformacao.'),
    ('Alice ne mangio uno.', 'Alice comeu um deles.', 'ne retoma uma parte de um conjunto.'),
    ('Divento di nuovo piccola.', 'Ficou pequena de novo.', 'di nuovo significa de novo.'),
    ('Scappo dalla casa.', 'Fugiu da casa.', 'scappare da indica fugir de um lugar.'),
    ('Entro in un bosco fitto.', 'Entrou em um bosque denso.', 'bosco fitto e bosque fechado/denso.'),
    ('Cerco qualcosa da mangiare.', 'Procurou algo para comer.', 'qualcosa da + infinitivo indica algo para fazer.'),
    ('Vide un fungo enorme.', 'Viu um cogumelo enorme.', 'fungo significa cogumelo.'),
    ('Sul fungo sedeva un bruco.', 'Sobre o cogumelo sentava uma lagarta.', 'sedeva e imperfeito de sedere.'),
    ('Il Bruco fumava un narghile.', 'A Lagarta fumava um narguile.', 'fumare significa fumar.'),
    ('Il Bruco guardo Alice con calma.', 'A Lagarta olhou Alice com calma.', 'con calma indica modo tranquilo.'),
    ('Chi sei tu?', 'Quem e voce?', 'chi sei tu e pergunta direta sobre identidade.'),
    ('Alice non sapeva rispondere.', 'Alice nao sabia responder.', 'sapere + infinitivo indica saber fazer algo.'),
    ('Era cambiata molte volte.', 'Ela tinha mudado muitas vezes.', 'cambiata concorda com Alice.'),
    ('Non era sicura di se.', 'Nao estava segura de si.', 'sicura di se significa segura de si.'),
    ('Il Bruco le fece altre domande.', 'A Lagarta lhe fez outras perguntas.', 'fare domande significa fazer perguntas.'),
    ('Alice rispose con fatica.', 'Alice respondeu com dificuldade.', 'con fatica indica esforco.'),
    ('Voglio tornare della mia altezza.', 'Quero voltar ao meu tamanho.', 'altezza significa altura.'),
    ('Un lato ti fara crescere.', 'Um lado fara voce crescer.', 'ti fara + infinitivo: fara voce fazer/ficar.'),
    ('L altro ti fara diminuire.', 'O outro fara voce diminuir.', 'l altro significa o outro.'),
    ('Parlava del fungo.', 'Falava do cogumelo.', 'parlava di significa falava sobre.'),
    ('Alice prese due pezzetti.', 'Alice pegou dois pedacinhos.', 'pezzetti e plural diminutivo de pezzo.'),
    ('Morse il pezzo di destra.', 'Mordeu o pedaco da direita.', 'destra significa direita.'),
    ('Il mento le batte sui piedi.', 'O queixo bateu nos pes dela.', 'mento significa queixo.'),
    ('Morse il pezzo di sinistra.', 'Mordeu o pedaco da esquerda.', 'sinistra significa esquerda.'),
    ('Il collo si allungo molto.', 'O pescoco se alongou muito.', 'allungarsi significa alongar-se.'),
    ('Un piccione la vide.', 'Um pombo a viu.', 'la retoma Alice como objeto direto.'),
    ('Il piccione la chiamo serpente.', 'O pombo a chamou de serpente.', 'chiamare qualcuno qualcosa: chamar alguem de algo.'),
    ('Alice nego con forza.', 'Alice negou com firmeza.', 'con forza significa com forca/firmeza.'),
    ('Non sono un serpente.', 'Nao sou uma serpente.', 'sono e primeira pessoa de essere.'),
    ('Sono una bambina.', 'Sou uma menina.', 'bambina significa menina.'),
    ('Il piccione non le credette.', 'O pombo nao acreditou nela.', 'credere a qualcuno significa acreditar em alguem.'),
    ('Alice mangio con prudenza.', 'Alice comeu com prudencia.', 'con prudenza indica cuidado.'),
    ('Ritorno alla giusta altezza.', 'Voltou a altura certa.', 'giusta significa certa ou adequada.'),
    ('Vide una casetta nel bosco.', 'Viu uma casinha no bosque.', 'casetta e diminutivo de casa.'),
    ('La casa era alta poco piu di un metro.', 'A casa tinha pouco mais de um metro de altura.', 'poco piu di significa pouco mais de.'),
    ('Alice si avvicino piano.', 'Alice se aproximou devagar.', 'avvicinarsi e aproximar-se.'),
    ('Un servo pesce bussava alla porta.', 'Um criado peixe batia a porta.', 'bussare alla porta significa bater a porta.'),
    ('Un servo rana apri.', 'Um criado sapo abriu.', 'aprire no passado remoto fica apri.'),
    ('Portava una lettera.', 'Levava uma carta.', 'portare significa levar ou carregar.'),
    ('La lettera era per la Duchessa.', 'A carta era para a Duquesa.', 'per indica destinatario.'),
    ('La Regina invitava la Duchessa.', 'A Rainha convidava a Duquesa.', 'invitare significa convidar.'),
    ('Alice entro senza invito.', 'Alice entrou sem convite.', 'senza significa sem.'),
    ('La cucina era piena di fumo.', 'A cozinha estava cheia de fumaca.', 'piena di significa cheia de.'),
    ('La cuoca mescolava una zuppa.', 'A cozinheira mexia uma sopa.', 'mescolare significa misturar ou mexer.'),
    ('C era troppo pepe.', 'Havia pimenta demais.', 'troppo indica excesso.'),
    ('Tutti starnutivano continuamente.', 'Todos espirravam continuamente.', 'starnutire significa espirrar.'),
    ('La Duchessa teneva un bambino.', 'A Duquesa segurava um bebe.', 'tenere pode significar segurar.'),
    ('Il bambino piangeva forte.', 'O bebe chorava alto.', 'piangere forte e chorar intensamente.'),
    ('La cuoca lanciava piatti.', 'A cozinheira arremessava pratos.', 'lanciare significa arremessar.'),
    ('Alice era molto confusa.', 'Alice estava muito confusa.', 'confusa concorda com Alice.'),
    ('Vide un gatto che sorrideva.', 'Viu um gato que sorria.', 'che sorrideva cria uma oracao relativa.'),
    ('Era il Gatto del Cheshire.', 'Era o Gato de Cheshire.', 'era identifica o personagem.'),
    ('Il gatto aveva un sorriso largo.', 'O gato tinha um sorriso largo.', 'sorriso largo significa sorriso amplo.'),
    ('Alice prese il bambino.', 'Alice pegou o bebe.', 'prendere pode ser pegar.'),
    ('Lo porto fuori dalla casa.', 'Levou-o para fora da casa.', 'lo porto junta objeto lo com porto.'),
    ('Il bambino grugniva come un maiale.', 'O bebe grunhia como um porco.', 'come un maiale e comparacao.'),
    ('Poco dopo divento un maialino.', 'Pouco depois virou um porquinho.', 'maialino e diminutivo de maiale.'),
    ('Alice lo lascio andare.', 'Alice o deixou ir.', 'lasciare andare significa deixar ir.'),
    ('Il Gatto apparve su un ramo.', 'O Gato apareceu sobre um galho.', 'apparire significa aparecer.'),
    ('Mi diresti dove andare?', 'Voce me diria para onde ir?', 'mi diresti e condicional educado.'),
    ('Dipende da dove vuoi arrivare.', 'Depende de onde voce quer chegar.', 'dipende da significa depende de.'),
    ('A me non importa molto.', 'Para mim nao importa muito.', 'importare usa a pessoa como objeto indireto.'),
    ('Allora non importa dove vai.', 'Entao nao importa para onde voce vai.', 'allora conecta a conclusao.'),
    ('Qui siamo tutti matti.', 'Aqui somos todos loucos.', 'matto significa louco.'),
    ('Anche tu sei matta.', 'Voce tambem e louca.', 'anche tu significa voce tambem.'),
    ('Il Gatto spari lentamente.', 'O Gato desapareceu lentamente.', 'sparire significa desaparecer.'),
    ('Rimase solo il sorriso.', 'Ficou apenas o sorriso.', 'rimase indica permaneceu.'),
    ('Alice arrivo a una casa.', 'Alice chegou a uma casa.', 'arrivare a indica chegar a um lugar.'),
    ('Davanti c era una tavola.', 'Na frente havia uma mesa.', 'davanti indica posicao frontal.'),
    ('Il Cappellaio prendeva il te.', 'O Chapeleiro tomava cha.', 'prendere il te significa tomar cha.'),
    ('La Lepre Marzolina era con lui.', 'A Lebre de Marco estava com ele.', 'con lui significa com ele.'),
    ('Un Ghiro dormiva tra loro.', 'Um Leirao dormia entre eles.', 'tra loro significa entre eles.'),
    ('Non c era posto.', 'Nao havia lugar.', 'posto significa lugar ou assento.'),
    ('C e molto posto.', 'Ha muito lugar.', 'c e significa ha ou existe.'),
    ('Alice si sedette a tavola.', 'Alice se sentou a mesa.', 'sedersi a tavola significa sentar-se a mesa.'),
    ('Prendi un po di vino.', 'Tome um pouco de vinho.', 'un po di significa um pouco de.'),
    ('Non vedo vino.', 'Nao vejo vinho.', 'vedere no presente: vedo.'),
    ('Infatti non ce n e.', 'De fato nao ha nenhum.', 'ce n e combina ha + disso.'),
    ('Non era molto educato.', 'Nao era muito educado.', 'educato significa educado.'),
    ('Il Cappellaio fece un indovinello.', 'O Chapeleiro fez uma adivinha.', 'indovinello significa adivinha.'),
    ('Alice penso molto.', 'Alice pensou muito.', 'molto intensifica o verbo.'),
    ('Non sapeva la risposta.', 'Nao sabia a resposta.', 'risposta significa resposta.'),
    ('Neanch io lo so.', 'Nem eu sei.', 'neanch io significa nem eu.'),
    ('Era un indovinello senza risposta.', 'Era uma adivinha sem resposta.', 'senza risposta significa sem resposta.'),
    ('Il tempo si era fermato.', 'O tempo tinha parado.', 'fermarsi e parar-se.'),
    ('Erano sempre le sei.', 'Eram sempre seis horas.', 'sempre significa sempre.'),
    ('Per questo prendevano sempre il te.', 'Por isso tomavam cha o tempo todo.', 'per questo significa por isso.'),
    ('Cambiarono posto molte volte.', 'Trocaram de lugar muitas vezes.', 'cambiare posto significa trocar de lugar.'),
    ('Alice si stanco della conversazione.', 'Alice se cansou da conversa.', 'stancarsi di significa cansar-se de.'),
    ('Se ne ando indignata.', 'Foi embora indignada.', 'andarsene indica ir embora.'),
    ('Entro in un giardino.', 'Entrou em um jardim.', 'entrare in indica entrar em.'),
    ('Vide tre giardinieri.', 'Viu tres jardineiros.', 'giardinieri significa jardineiros.'),
    ('Dipingevano rose bianche di rosso.', 'Pintavam rosas brancas de vermelho.', 'dipingere di rosso significa pintar de vermelho.'),
    ('Avevano piantato rose sbagliate.', 'Tinham plantado rosas erradas.', 'sbagliate significa erradas.'),
    ('La Regina amava le rose rosse.', 'A Rainha amava rosas vermelhas.', 'amare significa amar.'),
    ('Arrivo il corteo reale.', 'Chegou o cortejo real.', 'corteo reale e cortejo da realeza.'),
    ('La Regina era furiosa.', 'A Rainha estava furiosa.', 'furiosa concorda com Regina.'),
    ('Tagliategli la testa!', 'Cortem a cabeca dele!', 'tagliare la testa e expressao de ordem severa.'),
    ('Alice non ebbe paura.', 'Alice nao teve medo.', 'avere paura significa ter medo.'),
    ('Sono solo carte.', 'Sao apenas cartas.', 'solo significa apenas.'),
    ('La Regina invito Alice a giocare.', 'A Rainha convidou Alice para jogar.', 'invitare a + infinitivo indica convite.'),
    ('Giocavano a croquet.', 'Jogavam croque.', 'giocare a indica jogar um jogo.'),
    ('I fenicotteri erano mazze.', 'Os flamingos eram tacos.', 'mazze significa tacos ou bastoes.'),
    ('I ricci erano palle.', 'Os ouricos eram bolas.', 'palle significa bolas.'),
    ('Le carte facevano gli archi.', 'As cartas faziam os arcos.', 'fare gli archi significa formar os arcos.'),
    ('Nessuno seguiva le regole.', 'Ninguem seguia as regras.', 'seguire le regole significa seguir regras.'),
    ('La Regina urlava sempre.', 'A Rainha gritava sempre.', 'urlare significa gritar.'),
    ('Il Gatto apparve di nuovo.', 'O Gato apareceu de novo.', 'di nuovo significa novamente.'),
    ('Apparve solo la testa.', 'Apareceu apenas a cabeca.', 'solo la testa enfatiza parte visivel.'),
    ('Il Re voleva baciarne la mano.', 'O Rei queria beijar a mao dele.', 'baciarne usa ne para retomar o Gato.'),
    ('Ma il Gatto non aveva mani.', 'Mas o Gato nao tinha maos.', 'mani e plural de mano.'),
    ('La Duchessa torno libera.', 'A Duquesa voltou livre.', 'libera concorda com Duchessa.'),
    ('Parlava sempre di morale.', 'Falava sempre de moral.', 'parlare di significa falar sobre.'),
    ('Trova la morale in tutto.', 'Encontra moral em tudo.', 'in tutto significa em tudo.'),
    ('Alice non rispose subito.', 'Alice nao respondeu imediatamente.', 'subito significa imediatamente.'),
    ('La Regina mando via la Duchessa.', 'A Rainha mandou embora a Duquesa.', 'mandare via significa mandar embora.'),
    ('Alice segui il Grifone.', 'Alice seguiu o Grifo.', 'seguire significa seguir.'),
    ('Il Grifone la porto dalla Finta Tartaruga.', 'O Grifo a levou ate a Falsa Tartaruga.', 'portare da qualcuno e levar ate alguem.'),
    ('La Finta Tartaruga sospirava.', 'A Falsa Tartaruga suspirava.', 'sospirare significa suspirar.'),
    ('Racconto la sua scuola.', 'Contou sobre sua escola.', 'raccontare qualcosa significa contar algo.'),
    ('Studiava molte materie strane.', 'Estudava muitas materias estranhas.', 'materie significa materias escolares.'),
    ('Alice ascolto con pazienza.', 'Alice escutou com paciencia.', 'con pazienza indica modo paciente.'),
    ('Poi ballarono una quadriglia.', 'Depois dancaram uma quadrilha.', 'ballare significa dancar.'),
    ('La canzone era molto strana.', 'A cancao era muito estranha.', 'canzone significa cancao.'),
    ('Arrivo un richiamo al processo.', 'Chegou uma chamada para o julgamento.', 'processo significa julgamento.'),
    ('Tutti corsero al tribunale.', 'Todos correram ao tribunal.', 'tribunale significa tribunal.'),
    ('Il Re era il giudice.', 'O Rei era o juiz.', 'giudice significa juiz.'),
    ('La Regina sedeva accanto a lui.', 'A Rainha sentava-se ao lado dele.', 'accanto a significa ao lado de.'),
    ('Il Fante era accusato.', 'O Valete era acusado.', 'accusato significa acusado.'),
    ('Aveva rubato le crostate.', 'Tinha roubado as tortas.', 'rubare significa roubar.'),
    ('Il Cappellaio fu chiamato.', 'O Chapeleiro foi chamado.', 'fu chiamato e voz passiva no passado remoto.'),
    ('Aveva ancora il te in mano.', 'Ainda tinha o cha na mao.', 'in mano significa na mao.'),
    ('Alice cresceva di nuovo.', 'Alice crescia de novo.', 'cresceva mostra processo no passado.'),
    ('Non aveva piu paura.', 'Nao tinha mais medo.', 'non piu significa nao mais.'),
    ('Le carte volarono in aria.', 'As cartas voaram pelo ar.', 'in aria significa no ar.'),
    ('Alice si sveglio sulla riva.', 'Alice acordou na margem.', 'svegliarsi e acordar.'),
    ('La sorella era accanto a lei.', 'A irma estava ao lado dela.', 'accanto a lei significa ao lado dela.'),
    ('Era stato tutto un sogno.', 'Tudo tinha sido um sonho.', 'era stato e mais-que-perfeito de essere.'),
    ('Alice racconto la sua avventura.', 'Alice contou sua aventura.', 'avventura significa aventura.'),
    ('La sorella sorrise piano.', 'A irma sorriu suavemente.', 'sorridere significa sorrir.'),
    ('Alice corse a casa per il te.', 'Alice correu para casa para o cha.', 'per il te indica finalidade ou destino.'),
    ('Alice apri gli occhi lentamente.', 'Alice abriu os olhos lentamente.', 'aprire gli occhi significa abrir os olhos.'),
    ('Il sole stava tramontando.', 'O sol estava se pondo.', 'stare + gerundio indica acao em andamento.'),
    ('La sorella chiuse il libro.', 'A irma fechou o livro.', 'chiudere significa fechar.'),
    ('Il prato era tranquillo.', 'O gramado estava tranquilo.', 'prato significa gramado ou campo relvado.'),
    ('Il vento muoveva le foglie.', 'O vento movia as folhas.', 'muoveva e imperfeito de muovere.'),
    ('Alice ricordava il sogno.', 'Alice se lembrava do sonho.', 'ricordare pode ser lembrar; ricordarsi e lembrar-se.'),
    ('Tutto sembrava ancora vero.', 'Tudo ainda parecia real.', 'ancora aqui significa ainda.'),
    ('La voce del Coniglio tornava in mente.', 'A voz do Coelho voltava a mente.', 'tornare in mente significa vir a mente.'),
    ('Il giardino le pareva vicino.', 'O jardim lhe parecia perto.', 'le pareva significa parecia a ela.'),
    ('Le carte danzavano nel ricordo.', 'As cartas dancavam na lembranca.', 'nel ricordo significa na lembranca.'),
    ('Alice rise da sola.', 'Alice riu sozinha.', 'ridere no passado remoto fica rise.'),
    ('Che sogno strano!', 'Que sonho estranho!', 'che antes de substantivo cria exclamacao.'),
    ('La sorella ascolto con dolcezza.', 'A irma escutou com docura.', 'con dolcezza indica modo suave.'),
    ('Alice parlo velocemente.', 'Alice falou rapidamente.', 'velocemente e adverbio de modo.'),
    ('Racconto del Coniglio Bianco.', 'Contou sobre o Coelho Branco.', 'raccontare di significa contar sobre.'),
    ('Racconto della piccola porta.', 'Contou sobre a pequena porta.', 'della combina di + la.'),
    ('Racconto del giardino luminoso.', 'Contou sobre o jardim luminoso.', 'luminoso significa cheio de luz.'),
    ('Racconto della Regina cattiva.', 'Contou sobre a Rainha malvada.', 'cattiva concorda com Regina.'),
    ('La sorella immagino tutto.', 'A irma imaginou tudo.', 'immaginare significa imaginar.'),
    ('Anche lei vide il paese meraviglioso.', 'Ela tambem viu o pais maravilhoso.', 'anche lei significa ela tambem.'),
    ('Ma lo vide nella fantasia.', 'Mas o viu na imaginacao.', 'lo vide retoma o pais ou sonho.'),
    ('Il rumore del te sembrava vicino.', 'O som do cha parecia perto.', 'rumore pode ser som ou barulho.'),
    ('Il Cappellaio rideva nel sogno.', 'O Chapeleiro ria no sonho.', 'rideva e imperfeito de ridere.'),
    ('La Lepre parlava senza fermarsi.', 'A Lebre falava sem parar.', 'senza fermarsi significa sem parar.'),
    ('Il Ghiro dormiva profondamente.', 'O Leirao dormia profundamente.', 'profondamente intensifica dormir.'),
    ('Il Gatto sorrideva nell aria.', 'O Gato sorria no ar.', 'nell aria combina in + l aria.'),
    ('La Duchessa cercava morali.', 'A Duquesa procurava morais.', 'cercare significa procurar.'),
    ('La cuoca aggiungeva pepe.', 'A cozinheira acrescentava pimenta.', 'aggiungere significa acrescentar.'),
    ('Il bambino diventava maialino.', 'O bebe virava porquinho.', 'diventare indica transformacao.'),
    ('Il Bruco restava calmo.', 'A Lagarta permanecia calma.', 'restare significa ficar ou permanecer.'),
    ('Il fumo saliva piano.', 'A fumaca subia devagar.', 'salire significa subir.'),
    ('Il fungo cambiava tutto.', 'O cogumelo mudava tudo.', 'cambiare significa mudar.'),
    ('Un lato faceva crescere.', 'Um lado fazia crescer.', 'fare + infinitivo indica causar uma acao.'),
    ('Un lato faceva diminuire.', 'Um lado fazia diminuir.', 'diminuire significa diminuir.'),
    ('Alice doveva scegliere.', 'Alice precisava escolher.', 'dovere pode indicar necessidade.'),
    ('Scegliere non era facile.', 'Escolher nao era facil.', 'scegliere significa escolher.'),
    ('La curiosita la spingeva avanti.', 'A curiosidade a empurrava para frente.', 'spingere avanti significa empurrar adiante.'),
    ('La paura la fermava poco.', 'O medo a parava pouco.', 'fermare significa parar.'),
    ('Ogni porta prometteva qualcosa.', 'Cada porta prometia algo.', 'ogni usa singular.'),
    ('Ogni stanza era diversa.', 'Cada sala era diferente.', 'diversa concorda com stanza.'),
    ('Ogni domanda portava confusione.', 'Cada pergunta trazia confusao.', 'portare pode significar trazer.'),
    ('Alice cercava una risposta.', 'Alice procurava uma resposta.', 'risposta significa resposta.'),
    ('A volte trovava solo domande.', 'As vezes encontrava apenas perguntas.', 'a volte significa as vezes.'),
    ('Le parole cambiavano significato.', 'As palavras mudavam de significado.', 'significato significa significado.'),
    ('Le regole cambiavano sempre.', 'As regras mudavam sempre.', 'sempre significa sempre.'),
    ('Nessuno spiegava davvero.', 'Ninguem explicava de verdade.', 'davvero significa de verdade.'),
    ('Tutti parlavano insieme.', 'Todos falavam juntos.', 'insieme significa juntos.'),
    ('Alice cercava ordine.', 'Alice procurava ordem.', 'ordine significa ordem.'),
    ('Il paese amava il disordine.', 'O pais amava a desordem.', 'disordine e o contrario de ordine.'),
    ('Una domanda tirava l altra.', 'Uma pergunta puxava a outra.', 'tirare pode ser puxar.'),
    ('Una risposta spariva subito.', 'Uma resposta desaparecia logo.', 'sparire significa desaparecer.'),
    ('Il tempo correva strano.', 'O tempo corria estranho.', 'correre pode ser usado para o tempo passar.'),
    ('Le ore non obbedivano.', 'As horas nao obedeciam.', 'obbedire significa obedecer.'),
    ('Il sogno mescolava tutto.', 'O sonho misturava tudo.', 'mescolare significa misturar.'),
    ('Alice imparava senza accorgersene.', 'Alice aprendia sem perceber.', 'accorgersi significa perceber.'),
    ('Ogni errore diventava lezione.', 'Cada erro virava licao.', 'diventare indica virar/tornar-se.'),
    ('Ogni paura diventava gioco.', 'Cada medo virava jogo.', 'gioco significa jogo ou brincadeira.'),
    ('Ogni incontro portava parole nuove.', 'Cada encontro trazia palavras novas.', 'parole nuove significa palavras novas.'),
    ('La bambina osservava tutto.', 'A menina observava tudo.', 'osservare significa observar.'),
    ('Non capiva sempre.', 'Nao entendia sempre.', 'capire significa entender.'),
    ('Ma continuava a provare.', 'Mas continuava tentando.', 'continuare a + infinitivo indica persistencia.'),
    ('Provare era importante.', 'Tentar era importante.', 'provare significa tentar ou experimentar.'),
    ('Sbagliare non era la fine.', 'Errar nao era o fim.', 'sbagliare significa errar.'),
    ('Ricordare richiedeva tempo.', 'Lembrar exigia tempo.', 'richiedere significa exigir/requerer.'),
    ('Ripetere aiutava la memoria.', 'Repetir ajudava a memoria.', 'aiutare significa ajudar.'),
    ('Ascoltare aiutava la pronuncia.', 'Escutar ajudava a pronuncia.', 'pronuncia significa pronuncia.'),
    ('Parlare ad alta voce aiutava.', 'Falar em voz alta ajudava.', 'ad alta voce significa em voz alta.'),
    ('Alice ripeteva una frase.', 'Alice repetia uma frase.', 'ripetere significa repetir.'),
    ('Poi la diceva piu piano.', 'Depois a dizia mais devagar.', 'piu piano pode significar mais devagar.'),
    ('Poi la diceva piu forte.', 'Depois a dizia mais alto.', 'piu forte significa mais forte/alto.'),
    ('La frase diventava familiare.', 'A frase se tornava familiar.', 'familiare significa familiar.'),
    ('Una parola tornava spesso.', 'Uma palavra voltava frequentemente.', 'spesso significa frequentemente.'),
    ('Una parola nuova faceva paura.', 'Uma palavra nova dava medo.', 'fare paura significa dar medo.'),
    ('Dopo un po sembrava facile.', 'Depois de um tempo parecia facil.', 'dopo un po significa depois de um pouco/tempo.'),
    ('La memoria cresceva lentamente.', 'A memoria crescia lentamente.', 'lentamente e adverbio de modo.'),
    ('Il ricordo tornava al momento giusto.', 'A lembranca voltava no momento certo.', 'momento giusto significa momento certo.'),
    ('Alice sorrideva soddisfatta.', 'Alice sorria satisfeita.', 'soddisfatta concorda com Alice.'),
    ('Aveva imparato qualcosa.', 'Tinha aprendido algo.', 'imparare significa aprender.'),
    ('Non voleva dimenticare.', 'Nao queria esquecer.', 'dimenticare significa esquecer.'),
    ('Per questo ripeteva ancora.', 'Por isso repetia de novo.', 'per questo significa por isso.'),
    ('Una frase al giorno aiutava.', 'Uma frase por dia ajudava.', 'al giorno significa por dia.'),
    ('Venti frasi erano tante.', 'Vinte frases eram muitas.', 'tante concorda com frasi.'),
    ('Troppe frasi stancavano.', 'Frases demais cansavam.', 'troppe indica excesso no feminino plural.'),
    ('Le revisioni tornavano domani.', 'As revisoes voltavam amanha.', 'domani significa amanha.'),
    ('Alice doveva riposare.', 'Alice precisava descansar.', 'riposare significa descansar.'),
    ('Domani avrebbe ricordato meglio.', 'Amanha lembraria melhor.', 'avrebbe ricordato e condicional composto.'),
    ('Il giorno dopo riprese lo studio.', 'No dia seguinte retomou o estudo.', 'riprendere significa retomar.'),
    ('Prima ascolto la frase.', 'Primeiro escutou a frase.', 'prima pode significar primeiro.'),
    ('Poi provo a ripeterla.', 'Depois tentou repeti-la.', 'ripeterla junta ripetere + la.'),
    ('Poi guardo il testo.', 'Depois olhou o texto.', 'testo significa texto.'),
    ('Infine controllo la traduzione.', 'Por fim conferiu a traducao.', 'infine significa por fim.'),
    ('Questo metodo funzionava.', 'Esse metodo funcionava.', 'funzionare significa funcionar.'),
    ('La voce guidava l orecchio.', 'A voz guiava o ouvido.', 'orecchio significa ouvido.'),
    ('Il testo guidava gli occhi.', 'O texto guiava os olhos.', 'occhi significa olhos.'),
    ('La traduzione guidava il senso.', 'A traducao guiava o sentido.', 'senso significa sentido.'),
    ('La ripetizione fissava tutto.', 'A repeticao fixava tudo.', 'fissare pode significar fixar.'),
    ('Alice studiava con calma.', 'Alice estudava com calma.', 'con calma significa calmamente.'),
    ('Non correva piu troppo.', 'Nao corria mais demais.', 'non piu significa nao mais.'),
    ('Sceglieva poche frasi nuove.', 'Escolhia poucas frases novas.', 'poche concorda com frasi.'),
    ('Rivedeva molte frasi vecchie.', 'Revia muitas frases antigas.', 'rivedere significa rever.'),
    ('Cosi ricordava piu a lungo.', 'Assim lembrava por mais tempo.', 'piu a lungo significa por mais tempo.'),
    ('La sorella approvo il piano.', 'A irma aprovou o plano.', 'approvare significa aprovar.'),
    ('Un buon piano evita confusione.', 'Um bom plano evita confusao.', 'evitare significa evitar.'),
    ('Alice annui contenta.', 'Alice assentiu contente.', 'annuire significa assentir.'),
    ('Il quaderno era pronto.', 'O caderno estava pronto.', 'quaderno significa caderno.'),
    ('La matita era sul tavolo.', 'O lapis estava sobre a mesa.', 'matita significa lapis.'),
    ('Scrisse la prima frase.', 'Escreveu a primeira frase.', 'scrivere no passado remoto fica scrisse.'),
    ('La lesse tre volte.', 'Leu-a tres vezes.', 'la lesse retoma a frase.'),
    ('La ripete senza guardare.', 'Repetiu-a sem olhar.', 'senza guardare significa sem olhar.'),
    ('Poi passo alla frase seguente.', 'Depois passou para a frase seguinte.', 'seguente significa seguinte.'),
    ('Il ritmo era semplice.', 'O ritmo era simples.', 'semplice significa simples.'),
    ('Ascolta, ripeti, ricorda.', 'Escute, repita, lembre.', 'sao tres imperativos para rotina de estudo.'),
    ('Alice seguiva il ritmo.', 'Alice seguia o ritmo.', 'seguire significa seguir.'),
    ('La lingua sembrava meno lontana.', 'A lingua parecia menos distante.', 'meno significa menos.'),
    ('Le frasi aprivano una porta.', 'As frases abriam uma porta.', 'aprire una porta tambem funciona como metafora.'),
    ('Dietro la porta c era l italiano.', 'Atras da porta havia o italiano.', 'dietro la porta significa atras da porta.'),
    ('Alice cadde in una pozza di lacrime.', 'Alice caiu em uma poca de lagrimas.', 'pozza di lacrime significa poca de lagrimas.'),
    ('La pozza era molto salata.', 'A poca era muito salgada.', 'salata concorda com pozza, feminino singular.'),
    ('Un topo nuotava vicino a lei.', 'Um rato nadava perto dela.', 'nuotare significa nadar.'),
    ('Alice provo a parlare con il topo.', 'Alice tentou falar com o rato.', 'provare a + infinitivo indica tentar fazer algo.'),
    ('Il topo non amava i gatti.', 'O rato nao gostava de gatos.', 'amare aqui expressa gostar de algo.'),
    ('Alice capi di aver sbagliato argomento.', 'Alice entendeu que tinha errado o assunto.', 'aver sbagliato usa avere + participio.'),
    ('Gli animali uscirono dall acqua.', 'Os animais sairam da agua.', 'uscire da indica sair de algum lugar.'),
    ('Tutti erano bagnati e confusi.', 'Todos estavam molhados e confusos.', 'bagnati e confusi concordam com tutti.'),
    ('Il Dodo propose una corsa.', 'O Dodo propos uma corrida.', 'proporre no passado remoto fica propose.'),
    ('Nessuno sapeva dove cominciare.', 'Ninguem sabia onde comecar.', 'nessuno pede verbo no singular.'),
    ('Alla fine tutti vinsero.', 'No fim todos venceram.', 'alla fine significa no fim.'),
    ('Alice distribui piccoli premi.', 'Alice distribuiu pequenos premios.', 'distribui e passado remoto de distribuire.'),
    ('Poi trovo una casetta bianca.', 'Depois encontrou uma casinha branca.', 'casetta e diminutivo de casa.'),
    ('Il Coniglio cercava i guanti.', 'O Coelho procurava as luvas.', 'cercare significa procurar.'),
    ('Alice entro nella casetta.', 'Alice entrou na casinha.', 'entrare in significa entrar em.'),
    ('Bevve da una piccola bottiglia.', 'Bebeu de uma pequena garrafa.', 'bevve e passado remoto de bere.'),
    ('Subito divento enorme.', 'Imediatamente ficou enorme.', 'diventare significa tornar-se ou ficar.'),
    ('Il braccio usci dalla finestra.', 'O braco saiu pela janela.', 'uscire dalla finestra significa sair pela janela.'),
    ('Il Coniglio si spavento molto.', 'O Coelho se assustou muito.', 'spaventarsi significa assustar-se.'),
    ('Una folla si raduno fuori.', 'Uma multidao se reuniu do lado de fora.', 'radunarsi significa reunir-se.'),
    ('Alice mangio un piccolo dolce.', 'Alice comeu um pequeno doce.', 'dolce pode significar doce ou sobremesa.'),
    ('Finalmente torno piccola.', 'Finalmente voltou a ficar pequena.', 'tornare + adjetivo indica voltar a um estado.'),
    ('Nel bosco incontro un bruco.', 'No bosque encontrou uma lagarta.', 'bruco significa lagarta.'),
    ('Il Bruco fumava tranquillo.', 'A Lagarta fumava tranquila.', 'tranquillo descreve o modo calmo da cena.'),
    ('Chi sei tu?', 'Quem e voce?', 'chi sei tu e uma pergunta direta de identidade.'),
    ('Alice non sapeva rispondere.', 'Alice nao sabia responder.', 'sapere + infinitivo indica saber fazer algo.'),
    ('Era cambiata tante volte.', 'Ela tinha mudado muitas vezes.', 'era cambiata usa essere + participio.'),
    ('Il Bruco le diede un consiglio.', 'A Lagarta lhe deu um conselho.', 'le significa a ela.'),
    ('Un lato del fungo la faceva crescere.', 'Um lado do cogumelo a fazia crescer.', 'fungo significa cogumelo.'),
    ('L altro lato la faceva rimpicciolire.', 'O outro lado a fazia diminuir.', 'rimpicciolire significa ficar menor.'),
    ('Alice prese due pezzi di fungo.', 'Alice pegou dois pedacos de cogumelo.', 'pezzi di fungo significa pedacos de cogumelo.'),
]


def build_study_note(italian_text, focus):
    return (
        f'Foco da frase: {focus}\n'
        'Como revisar: leia o italiano, cubra a traducao e diga o sentido em voz alta antes de revelar.\n'
        'Depois compare palavra por palavra e escolha a nota pensando na facilidade de lembrar sem olhar.'
    )


def iter_alice_cards(limit=None):
    cards = ALICE_CARDS if limit is None else ALICE_CARDS[:limit]
    for index, (text, translation, focus) in enumerate(cards, start=1):
        yield {
            'deck_key': f'alice-{index:04d}',
            'order': index,
            'italian_text': text,
            'portuguese_text': translation,
            'study_note': build_study_note(text, focus),
        }
