# Production rule: append new cards to the end of this list. Do not reorder existing
# entries, because import_alice_phrases derives stable deck keys from the current
# position, such as alice-0001, alice-0002, and so on.
ALICE_CARDS = [
    ('Alice moriva di noia.', 'Alice estava morrendo de tédio.', 'moriva di noia é uma expressão idiomática: literalmente, morria de tédio.'),
    ('Se ne stava seduta con la sorella.', 'Ela estava sentada com a irmã.', 'se ne stava indica permanecer em certo estado ou lugar.'),
    ('Non faceva niente.', 'Ela não fazia nada.', 'non antes do verbo nega a ação; niente reforça a ideia de nada.'),
    ('Il libro non aveva figure.', 'O livro não tinha figuras.', 'aveva é o imperfeito de avere, usado para descrições no passado.'),
    ('Il libro non aveva dialoghi.', 'O livro não tinha diálogos.', 'dialoghi mostra o plural de dialogo; o h mantém o som duro de g.'),
    ('A cosa serve un libro?', 'Para que serve um livro?', 'a cosa serve pergunta a utilidade de algo.'),
    ('Pensava Alice.', 'Alice pensava.', 'pensava é imperfeito: uma ação mental em andamento no passado.'),
    ('Faceva molto caldo.', 'Fazia muito calor.', 'faceva caldo é a forma natural para falar do clima.'),
    ('Alice si sentiva assonnata.', 'Alice se sentia sonolenta.', 'sentirsi é reflexivo; si sentiva significa ela se sentia.'),
    ('Voleva fare una collana di margherite.', 'Ela queria fazer um colar de margaridas.', 'voleva fare combina querer com infinitivo: queria fazer.'),
    ('All improvviso passo un coniglio bianco.', 'De repente passou um coelho branco.', 'all improvviso marca uma mudança repentina na cena.'),
    ('Il coniglio aveva gli occhi rosa.', 'O coelho tinha olhos cor-de-rosa.', 'gli occhi usa gli antes de palavra masculina plural iniciada por vogal.'),
    ('Il Coniglio mormorava qualcosa.', 'O Coelho murmurava alguma coisa.', 'mormorava sugere fala baixa e contínua no passado.'),
    ('Ohime! Faro tardi!', 'Ai de mim! Vou me atrasar!', 'faro é futuro de fare; aqui significa vou fazer/ficar tarde.'),
    ('Alice non si meraviglio troppo.', 'Alice não ficou muito surpresa.', 'meravigliarsi é reflexivo: maravilhar-se ou surpreender-se.'),
    ('Tutto le parve naturale.', 'Tudo lhe pareceu natural.', 'le significa a ela; parve é passado remoto de parere.'),
    ('Il Coniglio tiro fuori un orologio.', 'O Coelho tirou um relógio.', 'tirare fuori significa tirar para fora.'),
    ('Lo guardo in fretta.', 'Ele o olhou rapidamente.', 'lo retoma orologio; in fretta quer dizer rapidamente.'),
    ('Poi corse via.', 'Depois saiu correndo.', 'correre via significa ir embora correndo.'),
    ('Alice balzo in piedi.', 'Alice deu um salto e ficou de pé.', 'balzare in piedi e levantar-se rapidamente.'),
    ('Le era venuta una grande curiosita.', 'Ela ficou com uma grande curiosidade.', 'le era venuta indica algo que veio a ela: surgiu nela.'),
    ('Corse attraverso il campo.', 'Ela correu pelo campo.', 'attraverso indica atravessar ou passar por um espaço.'),
    ('Il Coniglio entro nella tana.', 'O Coelho entrou na toca.', 'nella combina in + la; tana e toca.'),
    ('Alice gli corse dietro.', 'Alice correu atrás dele.', 'gli aqui significa a ele; correre dietro e correr atrás.'),
    ('Non penso a come sarebbe uscita.', 'Ela não pensou em como sairia.', 'sarebbe uscita é condicional passado: teria saido.'),
    ('La tana andava dritta.', 'A toca seguia em linha reta.', 'andava descreve direção; dritta significa reta.'),
    ('Poi scendeva all improvviso.', 'Depois descia de repente.', 'scendeva descreve movimento para baixo.'),
    ('Alice cadeva molto lentamente.', 'Alice caía muito lentamente.', 'lentamente e advérbio formado a partir de lento.'),
    ('Aveva tempo di guardarsi intorno.', 'Ela tinha tempo para olhar ao redor.', 'guardarsi intorno significa olhar ao redor.'),
    ('Vide scaffali e armadi.', 'Ela viu prateleiras e armários.', 'vide é passado remoto de vedere, comum em narrativa literária.'),
    ('Vide carte geografiche e quadri.', 'Ela viu mapas e quadros.', 'carte geografiche é o modo comum de dizer mapas.'),
    ('Prese un barattolo da uno scaffale.', 'Pegou um pote de uma prateleira.', 'prese é passado remoto de prendere.'),
    ('Sul barattolo c era scritto marmellata.', 'No pote estava escrito geleia.', 'sul combina su + il; c era significa havia/estava.'),
    ('Il barattolo era vuoto.', 'O pote estava vazio.', 'era é imperfeito de essere para descrição.'),
    ('Alice non volle lasciarlo cadere.', 'Alice não quis deixá-lo cair.', 'lasciarlo junta lasciare + lo: deixar ele.'),
    ('Lo rimise in un armadio.', 'Ela o colocou de volta em um armario.', 'rimettere indica colocar novamente ou devolver ao lugar.'),
    ('Giu, giu, giu.', 'Para baixo, para baixo, para baixo.', 'giu indica direção para baixo e cria ritmo narrativo.'),
    ('La caduta non finiva mai.', 'A queda nunca terminava.', 'non... mai corresponde a nunca.'),
    ('Alice comincio a parlare da sola.', 'Alice começou a falar sozinha.', 'cominciare a + infinitivo significa começar a fazer algo.'),
    ('Chissa quante miglia ho percorso.', 'Quem sabe quantas milhas eu percorri.', 'chissa expressa incerteza ou imaginação.'),
    ('Forse attraversero tutta la terra.', 'Talvez eu atravesse a terra inteira.', 'forse introduz possibilidade; attraversero está no futuro.'),
    ('Dina mi manchera molto.', 'Dina vai me fazer muita falta.', 'mi manchera segue a lógica italiana: ela faltará para mim.'),
    ('Dina e la mia gatta.', 'Dina é a minha gata.', 'mia concorda com gatta, feminino singular.'),
    ('Spero che si ricordino del suo latte.', 'Espero que se lembrem do leite dela.', 'spero che costuma pedir subjuntivo: si ricordino.'),
    ('Finalmente Alice arrivo in fondo.', 'Finalmente Alice chegou ao fundo.', 'in fondo significa no fundo ou ao final.'),
    ('Atterro su un mucchio di foglie.', 'Ela pousou sobre um monte de folhas.', 'atterrare e pousar; su indica sobre.'),
    ('Non si fece male.', 'Ela não se machucou.', 'farsi male significa machucar-se.'),
    ('Guardo in alto.', 'Ela olhou para cima.', 'in alto indica direção para cima.'),
    ('Tutto era buio sopra di lei.', 'Tudo estava escuro acima dela.', 'sopra di lei significa acima dela.'),
    ('Davanti a lei c era un lungo passaggio.', 'Diante dela havia uma longa passagem.', 'davanti a lei marca posição frontal.'),
    ('Il Coniglio correva ancora.', 'O Coelho ainda corria.', 'ancora aqui significa ainda.'),
    ('Alice parti come il vento.', 'Alice saiu como o vento.', 'come il vento e comparação de velocidade.'),
    ('Lo senti dire: Sono in ritardo.', 'Ela o ouviu dizer: Estou atrasado.', 'sentire + infinitivo pode significar ouvir alguém fazer algo.'),
    ('Svolto l angolo in fretta.', 'Dobrou a esquina rapidamente.', 'svoltare l angolo e virar a esquina.'),
    ('Alice gli fu alle calcagna.', 'Alice ficou nos calcanhares dele.', 'essere alle calcagna significa estar muito perto atrás.'),
    ('Si trovo in una sala lunga.', 'Ela se encontrou em uma sala longa.', 'trovarsi indica encontrar-se em um lugar.'),
    ('La sala era bassa e illuminata.', 'A sala era baixa e iluminada.', 'era descreve características do ambiente.'),
    ('Lampade pendevano dal soffitto.', 'Lâmpadas pendiam do teto.', 'pendere dal soffitto significa pender do teto.'),
    ('C erano porte tutto intorno.', 'Havia portas por todos os lados.', 'tutto intorno quer dizer ao redor inteiro.'),
    ('Le porte erano tutte chiuse.', 'As portas estavam todas fechadas.', 'chiuse concorda com porte, feminino plural.'),
    ('Alice provo ad aprirle.', 'Alice tentou abri-las.', 'aprirle junta aprire + le, retomando as portas.'),
    ('Non riusci ad aprirne nessuna.', 'Não conseguiu abrir nenhuma.', 'riuscire a indica conseguir; nessuna reforça nenhuma.'),
    ('Cammino triste nella sala.', 'Caminhou triste pela sala.', 'camminare descreve deslocamento a pé.'),
    ('Vide un tavolino di vetro.', 'Viu uma mesinha de vidro.', 'tavolino é diminutivo de tavolo.'),
    ('Sul tavolino c era una chiave.', 'Sobre a mesinha havia uma chave.', 'chiave é feminino em italiano: una chiave.'),
    ('La chiave era piccola e d oro.', 'A chave era pequena e de ouro.', 'd oro significa de ouro.'),
    ('Alice provo ogni porta.', 'Alice tentou cada porta.', 'ogni é singular mesmo com sentido de cada.'),
    ('La chiave non apriva niente.', 'A chave não abria nada.', 'niente funciona como objeto negativo.'),
    ('Poi vide una porticina.', 'Depois viu uma portinha.', 'porticina é diminutivo de porta.'),
    ('La porticina era dietro una tenda.', 'A portinha estava atrás de uma cortina.', 'dietro indica posição posterior.'),
    ('La chiave entro nella serratura.', 'A chave entrou na fechadura.', 'serratura e fechadura.'),
    ('Alice apri la porticina.', 'Alice abriu a portinha.', 'apri é passado remoto de aprire.'),
    ('Dietro c era un piccolo passaggio.', 'Atras havia uma pequena passagem.', 'piccolo concorda com passaggio, masculino singular.'),
    ('Il passaggio era stretto.', 'A passagem era estreita.', 'stretto descreve algo apertado ou estreito.'),
    ('Alice si inginocchio.', 'Alice se ajoelhou.', 'inginocchiarsi é verbo reflexivo.'),
    ('Guardo attraverso il passaggio.', 'Olhou através da passagem.', 'attraverso pode ser preposição: através de.'),
    ('Vide un giardino bellissimo.', 'Viu um jardim belíssimo.', 'bellissimo é superlativo: muito bonito.'),
    ('Voleva entrare nel giardino.', 'Ela queria entrar no jardim.', 'entrare in vira entrare nel antes de il.'),
    ('Ma era troppo grande.', 'Mas era grande demais.', 'troppo antes de adjetivo significa demais.'),
    ('Non poteva passare.', 'Ela não podia passar.', 'poteva é imperfeito de potere: podia.'),
    ('Torno al tavolino.', 'Voltou para a mesinha.', 'tornare a indica voltar para um lugar.'),
    ('Sperava di trovare un aiuto.', 'Esperava encontrar uma ajuda.', 'sperare di + infinitivo usa di.'),
    ('Trovo una bottiglietta.', 'Encontrou uma garrafinha.', 'bottiglietta é diminutivo de bottiglia.'),
    ('Sulla bottiglia c era un biglietto.', 'Na garrafa havia um bilhete.', 'biglietto pode ser bilhete ou etiqueta.'),
    ('Il biglietto diceva: bevimi.', 'O bilhete dizia: beba-me.', 'bevimi junta bevi + mi: beba-me.'),
    ('Alice lesse con attenzione.', 'Alice leu com atenção.', 'lesse é passado remoto de leggere.'),
    ('Controllo che non fosse veleno.', 'Verificou que não fosse veneno.', 'veleno significa veneno; fosse e subjuntivo.'),
    ('Non c era scritto veleno.', 'Não estava escrito veneno.', 'c era scritto é forma impessoal: estava escrito.'),
    ('Allora assaggio la bevanda.', 'Então provou a bebida.', 'allora organiza a sequência: então.'),
    ('Aveva un sapore strano.', 'Tinha um sabor estranho.', 'sapore é sabor; strano é estranho.'),
    ('Sembrava torta di ciliegie.', 'Parecia torta de cerejas.', 'sembrava indica aparência ou impressao.'),
    ('Sembrava crema e ananas.', 'Parecia creme e abacaxi.', 'sembrava se repete para listar sensações.'),
    ('Sembrava tacchino arrosto.', 'Parecia peru assado.', 'arrosto significa assado.'),
    ('Alice fini la bottiglietta.', 'Alice terminou a garrafinha.', 'finire pode significar terminar ou acabar.'),
    ('Che sensazione curiosa!', 'Que sensação curiosa!', 'che antes de nome cria exclamação.'),
    ('Sto diventando piccola.', 'Estou ficando pequena.', 'stare + gerúndio indica ação em progresso.'),
    ('Divento alta solo venticinque centimetri.', 'Ficou com apenas vinte e cinco centimetros.', 'solo enfatiza apenas.'),
    ('Ora poteva passare dalla porta.', 'Agora podia passar pela porta.', 'ora significa agora.'),
    ('Ma aveva dimenticato la chiave.', 'Mas havia esquecido a chave.', 'dimenticare significa esquecer.'),
    ('La chiave era sul tavolino.', 'A chave estava sobre a mesinha.', 'sul tavolino retoma o local importante.'),
    ('Alice non poteva raggiungerla.', 'Alice não podia alcançá-la.', 'raggiungerla junta raggiungere + la.'),
    ('Provo ad arrampicarsi.', 'Tentou escalar.', 'arrampicarsi é subir/escalar usando esforco.'),
    ('Scivolo di nuovo giu.', 'Escorregou de novo para baixo.', 'di nuovo significa de novo.'),
    ('Si sedette e pianse.', 'Sentou-se e chorou.', 'sedersi é reflexivo; si sedette é passado remoto.'),
    ('Basta piangere.', 'Chega de chorar.', 'basta + infinitivo expressa parar/chega de.'),
    ('Disse Alice a se stessa.', 'Disse Alice a si mesma.', 'a se stessa indica para si mesma.'),
    ('Poco dopo vide una scatola.', 'Pouco depois viu uma caixa.', 'poco dopo marca tempo: pouco depois.'),
    ('Dentro c era una torta.', 'Dentro havia um bolo.', 'dentro indica interior.'),
    ('Sulla torta era scritto: mangiami.', 'No bolo estava escrito: coma-me.', 'mangiami junta mangia + mi.'),
    ('Alice mangio un pezzetto.', 'Alice comeu um pedacinho.', 'pezzetto é diminutivo de pezzo.'),
    ('Aspetto qualche minuto.', 'Esperou alguns minutos.', 'qualche usa singular: qualche minuto.'),
    ('Non successe niente.', 'Não aconteceu nada.', 'succedere significa acontecer.'),
    ('Allora mangio tutta la torta.', 'Então comeu o bolo inteiro.', 'tutta concorda com torta, feminino singular.'),
    ('Alice crebbe rapidamente.', 'Alice cresceu rapidamente.', 'crescere vira crebbe no passado remoto.'),
    ('La testa tocco il soffitto.', 'A cabeça tocou o teto.', 'toccare significa tocar ou encostar.'),
    ('Prese subito la chiave.', 'Pegou imediatamente a chave.', 'subito significa imediatamente.'),
    ('Corse verso la porticina.', 'Correu em direção a portinha.', 'verso indica direção.'),
    ('Ora era troppo alta.', 'Agora estava alta demais.', 'troppo alta significa alta demais.'),
    ('Poteva solo guardare il giardino.', 'Podia apenas olhar o jardim.', 'solo pode significar apenas.'),
    ('Si mise a piangere di nuovo.', 'Começou a chorar de novo.', 'mettersi a + infinitivo significa começar a fazer.'),
    ('Le lacrime cadevano a terra.', 'As lágrimas caíam no chão.', 'lacrime é plural feminino.'),
    ('Si formo una grande pozza.', 'Formou-se uma grande poça.', 'formarsi indica formar-se.'),
    ('Alice si sgrido severamente.', 'Alice repreendeu a si mesma severamente.', 'sgridarsi e repreender-se.'),
    ('Non serve piangere così.', 'Não adianta chorar assim.', 'servire aqui indica ter utilidade.'),
    ('Poco dopo senti dei passi.', 'Pouco depois ouviu passos.', 'sentire pode ser ouvir.'),
    ('Era il Coniglio Bianco.', 'Era o Coelho Branco.', 'era identifica quem apareceu.'),
    ('Portava guanti bianchi.', 'Usava luvas brancas.', 'portare pode significar usar/vestir acessórios.'),
    ('Portava anche un ventaglio.', 'Levava também um leque.', 'anche significa também.'),
    ('Sembrava molto preoccupato.', 'Parecia muito preocupado.', 'preoccupato e preocupado.'),
    ('Mormorava tra se.', 'Murmurava consigo mesmo.', 'tra se significa consigo mesmo.'),
    ('La Duchessa mi fara tagliare la testa.', 'A Duquesa mandará cortar minha cabeça.', 'mi fará + infinitivo indica fará comigo.'),
    ('Alice provo a parlargli.', 'Alice tentou falar com ele.', 'parlargli junta parlare + gli.'),
    ('Il Coniglio si spavento.', 'O Coelho se assustou.', 'spaventarsi e assustar-se.'),
    ('Lascio cadere guanti e ventaglio.', 'Deixou cair luvas e leque.', 'lasciare cadere significa deixar cair.'),
    ('Poi scappo nel buio.', 'Depois fugiu no escuro.', 'scappare é fugir.'),
    ('Alice raccolse il ventaglio.', 'Alice recolheu o leque.', 'raccogliere é pegar algo do chão.'),
    ('Faceva molto caldo nella sala.', 'Fazia muito calor na sala.', 'nella combina in + la.'),
    ('Si fece vento con il ventaglio.', 'Abanou-se com o leque.', 'farsi vento e abanar-se.'),
    ('Comincio a diventare piccola.', 'Começou a ficar pequena.', 'diventare indica transformação.'),
    ('Lascia cadere il ventaglio.', 'Deixa cair o leque.', 'o presente aqui deixa a ação viva e direta.'),
    ('Era quasi scomparsa.', 'Ela quase havia desaparecido.', 'quasi significa quase.'),
    ('Corse subito verso la porta.', 'Correu imediatamente para a porta.', 'verso mostra direção para um alvo.'),
    ('La porta era ancora chiusa.', 'A porta ainda estava fechada.', 'ancora aqui significa ainda.'),
    ('La chiave era di nuovo sul tavolo.', 'A chave estava novamente sobre a mesa.', 'di nuovo significa novamente.'),
    ('Alice scivolo e cadde nell acqua.', 'Alice escorregou e caiu na água.', 'cadere nell acqua: cair na água.'),
    ('Era la pozza delle sue lacrime.', 'Era a poça das suas lágrimas.', 'sue concorda com lacrime.'),
    ('Ora nuotava nella pozza.', 'Agora nadava na poça.', 'nuotare é nadar.'),
    ('Vide un topo vicino a lei.', 'Viu um rato perto dela.', 'vicino a lei significa perto dela.'),
    ('Il topo nuotava bene.', 'O rato nadava bem.', 'bene e advérbio: bem.'),
    ('Alice parlo al topo.', 'Alice falou com o rato.', 'parlare a/con alguém: falar com alguém.'),
    ('Forse capisce il francese.', 'Talvez entenda francês.', 'forse expressa possibilidade.'),
    ('Il topo salto di paura.', 'O rato saltou de medo.', 'di paura indica causa: por medo.'),
    ('Alice chiese scusa.', 'Alice pediu desculpa.', 'chiedere scusa é pedir desculpa.'),
    ('Non voleva parlare di gatti.', 'Não queria falar de gatos.', 'parlare di significa falar sobre.'),
    ('Il topo odiava i gatti.', 'O rato odiava gatos.', 'odiava é imperfeito de odiare.'),
    ('Arrivarono altri animali.', 'Chegaram outros animais.', 'arrivare usa essere nos tempos compostos, mas aqui e passato remoto.'),
    ('Tutti nuotavano nella pozza.', 'Todos nadavam na poça.', 'tutti indica todos.'),
    ('La riva era vicina.', 'A margem estava perto.', 'riva é margem.'),
    ('Uscirono dall acqua bagnati.', 'Saíram da água molhados.', 'dall acqua combina da + l acqua.'),
    ('Erano tutti molto bagnati.', 'Todos estavam muito molhados.', 'bagnati concorda com tutti, masculino plural.'),
    ('Il topo sembrava arrabbiato.', 'O rato parecia irritado.', 'sembrava descreve aparência ou impressao.'),
    ('Alice ascoltava con attenzione.', 'Alice escutava com atenção.', 'ascoltare e escutar de modo intencional.'),
    ('Il topo racconto una storia.', 'O rato contou uma história.', 'raccontare significa contar uma história.'),
    ('La storia era lunga e triste.', 'A história era longa e triste.', 'lunga e triste concordam com storia.'),
    ('Alice penso alla coda del topo.', 'Alice pensou na cauda do rato.', 'coda pode significar cauda ou fila.'),
    ('Il topo si offese.', 'O rato se ofendeu.', 'offendersi é verbo reflexivo.'),
    ('Se ne ando in fretta.', 'Foi embora rapidamente.', 'andarsene significa ir embora.'),
    ('Alice rimase sola per un momento.', 'Alice ficou sozinha por um momento.', 'rimanere indica permanecer ou ficar.'),
    ('Gli animali volevano asciugarsi.', 'Os animais queriam se secar.', 'asciugarsi e secar-se.'),
    ('Il Dodo propose una corsa.', 'O Dodo propos uma corrida.', 'propose é passado remoto de proporre.'),
    ('Tutti cominciarono a correre.', 'Todos começaram a correr.', 'cominciare a + infinitivo indica início de ação.'),
    ('Nessuno sapeva dove andare.', 'Ninguem sabia para onde ir.', 'nessuno significa ninguém.'),
    ('La corsa duro mezz ora.', 'A corrida durou meia hora.', 'durare indica duração.'),
    ('Alla fine erano asciutti.', 'No fim estavam secos.', 'alla fine significa no fim.'),
    ('Il Dodo disse che tutti avevano vinto.', 'O Dodo disse que todos tinham vencido.', 'avevano vinto e mais-que-perfeito composto.'),
    ('Alice doveva dare i premi.', 'Alice devia dar os prêmios.', 'dovere no imperfeito indica obrigação.'),
    ('Trovo dei confetti in tasca.', 'Encontrou confeitos no bolso.', 'in tasca significa no bolso.'),
    ('Diede un confetto a ciascuno.', 'Deu um confeito a cada um.', 'ciascuno significa cada um.'),
    ('Anche Alice ricevette un premio.', 'Alice também recebeu um prêmio.', 'anche significa também.'),
    ('Il premio era il suo ditale.', 'O prêmio era o seu dedal.', 'ditale significa dedal.'),
    ('Tutti applaudirono con serieta.', 'Todos aplaudiram com seriedade.', 'applaudire significa aplaudir.'),
    ('Alice parlo di nuovo di Dina.', 'Alice falou de novo de Dina.', 'di nuovo significa novamente.'),
    ('Gli animali ebbero paura.', 'Os animais tiveram medo.', 'avere paura significa ter medo.'),
    ('Uno dopo l altro andarono via.', 'Um depois do outro foram embora.', 'uno dopo l altro indica sequência.'),
    ('Alice si senti molto sola.', 'Alice se sentiu muito sozinha.', 'sentirsi é reflexivo.'),
    ('Pianse ancora un poco.', 'Chorou ainda um pouco.', 'ancora un poco significa ainda um pouco.'),
    ('Poi senti dei passi piccoli.', 'Depois ouviu passos pequenos.', 'passi piccoli descreve passos pequenos.'),
    ('Il Coniglio tornava di corsa.', 'O Coelho voltava correndo.', 'tornare significa voltar.'),
    ('Cercava guanti e ventaglio.', 'Procurava luvas e leque.', 'cercare significa procurar.'),
    ('Alice si spavento e scappo.', 'Alice se assustou e fugiu.', 'spaventarsi e assustar-se.'),
    ('Il Coniglio la chiamo Mary Ann.', 'O Coelho a chamou de Mary Ann.', 'chiamare qualcuno indica chamar alguém.'),
    ('Le ordino di andare a casa.', 'Ordenou que ela fosse para casa.', 'ordinare di + infinitivo indica ordem.'),
    ('Alice obbedi senza discutere.', 'Alice obedeceu sem discutir.', 'senza + infinitivo significa sem fazer algo.'),
    ('Entro in una piccola casa.', 'Entrou em uma pequena casa.', 'entrare in indica entrar em lugar.'),
    ('Sali le scale in fretta.', 'Subiu as escadas rapidamente.', 'salire le scale é subir escadas.'),
    ('Trovo una stanza ordinata.', 'Encontrou um quarto arrumado.', 'ordinata significa arrumada ou organizada.'),
    ('Sul tavolo c era una bottiglia.', 'Sobre a mesa havia uma garrafa.', 'sul tavolo combina su + il.'),
    ('Alice bevve senza pensarci troppo.', 'Alice bebeu sem pensar muito nisso.', 'pensarci significa pensar nisso.'),
    ('Comincio a crescere subito.', 'Começou a crescer imediatamente.', 'crescere indica aumento de tamanho.'),
    ('Il corpo riempi la stanza.', 'O corpo encheu o quarto.', 'riempire significa encher.'),
    ('Un braccio usci dalla finestra.', 'Um braço saiu pela janela.', 'uscire dalla finestra: sair pela janela.'),
    ('Un piede entro nel camino.', 'Um pé entrou na chamine.', 'camino significa lareira ou chamine.'),
    ('Alice non poteva muoversi.', 'Alice não podia se mover.', 'muoversi e mover-se.'),
    ('Il Coniglio arrivo alla porta.', 'O Coelho chegou a porta.', 'arrivare a indica chegar a um lugar.'),
    ('Provo ad aprire la porta.', 'Tentou abrir a porta.', 'provare a + infinitivo significa tentar.'),
    ('La porta non si apriva.', 'A porta não abria.', 'si apriva pode indicar abertura por si.'),
    ('Chiamo aiuto a gran voce.', 'Chamou ajuda em voz alta.', 'a gran voce significa em voz alta.'),
    ('Arrivo una lucertola di nome Bill.', 'Chegou um lagarto chamado Bill.', 'di nome introduz o nome de alguém.'),
    ('Bill sali sul tetto.', 'Bill subiu no telhado.', 'sul tetto significa sobre/no telhado.'),
    ('Alice senti rumori nel camino.', 'Alice ouviu barulhos na chamine.', 'rumori significa barulhos.'),
    ('Diede un calcio con il piede.', 'Deu um chute com o pé.', 'dare un calcio significa chutar.'),
    ('Bill volo fuori dal camino.', 'Bill voou para fora da chamine.', 'fuori da significa para fora de.'),
    ('I sassolini diventavano dolcetti.', 'As pedrinhas viravam docinhos.', 'diventare indica transformação.'),
    ('Alice ne mangio uno.', 'Alice comeu um deles.', 'ne retoma uma parte de um conjunto.'),
    ('Divento di nuovo piccola.', 'Ficou pequena de novo.', 'di nuovo significa de novo.'),
    ('Scappo dalla casa.', 'Fugiu da casa.', 'scappare da indica fugir de um lugar.'),
    ('Entro in un bosco fitto.', 'Entrou em um bosque denso.', 'bosco fitto e bosque fechado/denso.'),
    ('Cerco qualcosa da mangiare.', 'Procurou algo para comer.', 'qualcosa da + infinitivo indica algo para fazer.'),
    ('Vide un fungo enorme.', 'Viu um cogumelo enorme.', 'fungo significa cogumelo.'),
    ('Sul fungo sedeva un bruco.', 'Sobre o cogumelo sentava uma lagarta.', 'sedeva é imperfeito de sedere.'),
    ('Il Bruco fumava un narghile.', 'A Lagarta fumava um narguile.', 'fumare significa fumar.'),
    ('Il Bruco guardo Alice con calma.', 'A Lagarta olhou Alice com calma.', 'con calma indica modo tranquilo.'),
    ('Chi sei tu?', 'Quem é você?', 'chi sei tu é pergunta direta sobre identidade.'),
    ('Alice non sapeva rispondere.', 'Alice não sabia responder.', 'sapere + infinitivo indica saber fazer algo.'),
    ('Era cambiata molte volte.', 'Ela tinha mudado muitas vezes.', 'cambiata concorda com Alice.'),
    ('Non era sicura di se.', 'Não estava segura de si.', 'sicura di se significa segura de si.'),
    ('Il Bruco le fece altre domande.', 'A Lagarta lhe fez outras perguntas.', 'fare domande significa fazer perguntas.'),
    ('Alice rispose con fatica.', 'Alice respondeu com dificuldade.', 'con fatica indica esforco.'),
    ('Voglio tornare della mia altezza.', 'Quero voltar ao meu tamanho.', 'altezza significa altura.'),
    ('Un lato ti fara crescere.', 'Um lado fará você crescer.', 'ti fará + infinitivo: fará você fazer/ficar.'),
    ('L altro ti fara diminuire.', 'O outro fará você diminuir.', 'l altro significa o outro.'),
    ('Parlava del fungo.', 'Falava do cogumelo.', 'parlava di significa falava sobre.'),
    ('Alice prese due pezzetti.', 'Alice pegou dois pedacinhos.', 'pezzetti é plural diminutivo de pezzo.'),
    ('Morse il pezzo di destra.', 'Mordeu o pedaco da direita.', 'destra significa direita.'),
    ('Il mento le batte sui piedi.', 'O queixo bateu nos pes dela.', 'mento significa queixo.'),
    ('Morse il pezzo di sinistra.', 'Mordeu o pedaco da esquerda.', 'sinistra significa esquerda.'),
    ('Il collo si allungo molto.', 'O pescoco se alongou muito.', 'allungarsi significa alongar-se.'),
    ('Un piccione la vide.', 'Um pombo a viu.', 'la retoma Alice como objeto direto.'),
    ('Il piccione la chiamo serpente.', 'O pombo a chamou de serpente.', 'chiamare qualcuno qualcosa: chamar alguém de algo.'),
    ('Alice nego con forza.', 'Alice negou com firmeza.', 'con forza significa com forca/firmeza.'),
    ('Non sono un serpente.', 'Não sou uma serpente.', 'sono e primeira pessoa de essere.'),
    ('Sono una bambina.', 'Sou uma menina.', 'bambina significa menina.'),
    ('Il piccione non le credette.', 'O pombo não acreditou nela.', 'credere a qualcuno significa acreditar em alguém.'),
    ('Alice mangio con prudenza.', 'Alice comeu com prudencia.', 'con prudenza indica cuidado.'),
    ('Ritorno alla giusta altezza.', 'Voltou a altura certa.', 'giusta significa certa ou adequada.'),
    ('Vide una casetta nel bosco.', 'Viu uma casinha no bosque.', 'casetta é diminutivo de casa.'),
    ('La casa era alta poco piu di un metro.', 'A casa tinha pouco mais de um metro de altura.', 'poco piu di significa pouco mais de.'),
    ('Alice si avvicino piano.', 'Alice se aproximou devagar.', 'avvicinarsi e aproximar-se.'),
    ('Un servo pesce bussava alla porta.', 'Um criado peixe batia a porta.', 'bussare alla porta significa bater a porta.'),
    ('Un servo rana apri.', 'Um criado sapo abriu.', 'aprire no passado remoto fica apri.'),
    ('Portava una lettera.', 'Levava uma carta.', 'portare significa levar ou carregar.'),
    ('La lettera era per la Duchessa.', 'A carta era para a Duquesa.', 'per indica destinatario.'),
    ('La Regina invitava la Duchessa.', 'A Rainha convidava a Duquesa.', 'invitare significa convidar.'),
    ('Alice entro senza invito.', 'Alice entrou sem convite.', 'senza significa sem.'),
    ('La cucina era piena di fumo.', 'A cozinha estava cheia de fumaca.', 'piena di significa cheia de.'),
    ('La cuoca mescolava una zuppa.', 'A cozinheira mexia uma sopa.', 'mescolare significa misturar ou mexer.'),
    ('C era troppo pepe.', 'Havia pimenta demais.', 'troppo indica excesso.'),
    ('Tutti starnutivano continuamente.', 'Todos espirravam continuamente.', 'starnutire significa espirrar.'),
    ('La Duchessa teneva un bambino.', 'A Duquesa segurava um bebê.', 'tenere pode significar segurar.'),
    ('Il bambino piangeva forte.', 'O bebê chorava alto.', 'piangere forte e chorar intensamente.'),
    ('La cuoca lanciava piatti.', 'A cozinheira arremessava pratos.', 'lanciare significa arremessar.'),
    ('Alice era molto confusa.', 'Alice estava muito confusa.', 'confusa concorda com Alice.'),
    ('Vide un gatto che sorrideva.', 'Viu um gato que sorria.', 'che sorrideva cria uma oração relativa.'),
    ('Era il Gatto del Cheshire.', 'Era o Gato de Cheshire.', 'era identifica o personagem.'),
    ('Il gatto aveva un sorriso largo.', 'O gato tinha um sorriso largo.', 'sorriso largo significa sorriso amplo.'),
    ('Alice prese il bambino.', 'Alice pegou o bebê.', 'prendere pode ser pegar.'),
    ('Lo porto fuori dalla casa.', 'Levou-o para fora da casa.', 'lo porto junta objeto lo com porto.'),
    ('Il bambino grugniva come un maiale.', 'O bebê grunhia como um porco.', 'come un maiale e comparação.'),
    ('Poco dopo divento un maialino.', 'Pouco depois virou um porquinho.', 'maialino é diminutivo de maiale.'),
    ('Alice lo lascio andare.', 'Alice o deixou ir.', 'lasciare andare significa deixar ir.'),
    ('Il Gatto apparve su un ramo.', 'O Gato apareceu sobre um galho.', 'apparire significa aparecer.'),
    ('Mi diresti dove andare?', 'Você me diria para onde ir?', 'mi diresti é condicional educado.'),
    ('Dipende da dove vuoi arrivare.', 'Depende de onde você quer chegar.', 'dipende da significa depende de.'),
    ('A me non importa molto.', 'Para mim não importa muito.', 'importare usa a pessoa como objeto indireto.'),
    ('Allora non importa dove vai.', 'Então não importa para onde você vai.', 'allora conecta a conclusão.'),
    ('Qui siamo tutti matti.', 'Aqui somos todos loucos.', 'matto significa louco.'),
    ('Anche tu sei matta.', 'Você também e louca.', 'anche tu significa você também.'),
    ('Il Gatto spari lentamente.', 'O Gato desapareceu lentamente.', 'sparire significa desaparecer.'),
    ('Rimase solo il sorriso.', 'Ficou apenas o sorriso.', 'rimase indica permaneceu.'),
    ('Alice arrivo a una casa.', 'Alice chegou a uma casa.', 'arrivare a indica chegar a um lugar.'),
    ('Davanti c era una tavola.', 'Na frente havia uma mesa.', 'davanti indica posição frontal.'),
    ('Il Cappellaio prendeva il te.', 'O Chapeleiro tomava chá.', 'prendere il te significa tomar chá.'),
    ('La Lepre Marzolina era con lui.', 'A Lebre de Marco estava com ele.', 'con lui significa com ele.'),
    ('Un Ghiro dormiva tra loro.', 'Um Leirao dormia entre eles.', 'tra loro significa entre eles.'),
    ('Non c era posto.', 'Não havia lugar.', 'posto significa lugar ou assento.'),
    ('C e molto posto.', 'Ha muito lugar.', 'c e significa há ou existe.'),
    ('Alice si sedette a tavola.', 'Alice se sentou a mesa.', 'sedersi a tavola significa sentar-se a mesa.'),
    ('Prendi un po di vino.', 'Tome um pouco de vinho.', 'un po di significa um pouco de.'),
    ('Non vedo vino.', 'Não vejo vinho.', 'vedere no presente: vedo.'),
    ('Infatti non ce n e.', 'De fato não há nenhum.', 'ce n e combina há + disso.'),
    ('Non era molto educato.', 'Não era muito educado.', 'educato significa educado.'),
    ('Il Cappellaio fece un indovinello.', 'O Chapeleiro fez uma adivinha.', 'indovinello significa adivinha.'),
    ('Alice penso molto.', 'Alice pensou muito.', 'molto intensifica o verbo.'),
    ('Non sapeva la risposta.', 'Não sabia a resposta.', 'risposta significa resposta.'),
    ('Neanch io lo so.', 'Nem eu sei.', 'neanch io significa nem eu.'),
    ('Era un indovinello senza risposta.', 'Era uma adivinha sem resposta.', 'senza risposta significa sem resposta.'),
    ('Il tempo si era fermato.', 'O tempo tinha parado.', 'fermarsi e parar-se.'),
    ('Erano sempre le sei.', 'Eram sempre seis horas.', 'sempre significa sempre.'),
    ('Per questo prendevano sempre il te.', 'Por isso tomavam chá o tempo todo.', 'per questo significa por isso.'),
    ('Cambiarono posto molte volte.', 'Trocaram de lugar muitas vezes.', 'cambiare posto significa trocar de lugar.'),
    ('Alice si stanco della conversazione.', 'Alice se cansou da conversa.', 'stancarsi di significa cansar-se de.'),
    ('Se ne ando indignata.', 'Foi embora indignada.', 'andarsene indica ir embora.'),
    ('Entro in un giardino.', 'Entrou em um jardim.', 'entrare in indica entrar em.'),
    ('Vide tre giardinieri.', 'Viu três jardineiros.', 'giardinieri significa jardineiros.'),
    ('Dipingevano rose bianche di rosso.', 'Pintavam rosas brancas de vermelho.', 'dipingere di rosso significa pintar de vermelho.'),
    ('Avevano piantato rose sbagliate.', 'Tinham plantado rosas erradas.', 'sbagliate significa erradas.'),
    ('La Regina amava le rose rosse.', 'A Rainha amava rosas vermelhas.', 'amare significa amar.'),
    ('Arrivo il corteo reale.', 'Chegou o cortejo real.', 'corteo reale e cortejo da realeza.'),
    ('La Regina era furiosa.', 'A Rainha estava furiosa.', 'furiosa concorda com Regina.'),
    ('Tagliategli la testa!', 'Cortem a cabeça dele!', 'tagliare la testa e expressão de ordem severa.'),
    ('Alice non ebbe paura.', 'Alice não teve medo.', 'avere paura significa ter medo.'),
    ('Sono solo carte.', 'Sao apenas cartas.', 'solo significa apenas.'),
    ('La Regina invito Alice a giocare.', 'A Rainha convidou Alice para jogar.', 'invitare a + infinitivo indica convite.'),
    ('Giocavano a croquet.', 'Jogavam croque.', 'giocare a indica jogar um jogo.'),
    ('I fenicotteri erano mazze.', 'Os flamingos eram tacos.', 'mazze significa tacos ou bastoes.'),
    ('I ricci erano palle.', 'Os ouricos eram bolas.', 'palle significa bolas.'),
    ('Le carte facevano gli archi.', 'As cartas faziam os arcos.', 'fare gli archi significa formar os arcos.'),
    ('Nessuno seguiva le regole.', 'Ninguem seguia as regras.', 'seguire le regole significa seguir regras.'),
    ('La Regina urlava sempre.', 'A Rainha gritava sempre.', 'urlare significa gritar.'),
    ('Il Gatto apparve di nuovo.', 'O Gato apareceu de novo.', 'di nuovo significa novamente.'),
    ('Apparve solo la testa.', 'Apareceu apenas a cabeça.', 'solo la testa enfatiza parte visivel.'),
    ('Il Re voleva baciarne la mano.', 'O Rei queria beijar a mao dele.', 'baciarne usa ne para retomar o Gato.'),
    ('Ma il Gatto non aveva mani.', 'Mas o Gato não tinha mãos.', 'mani é plural de mano.'),
    ('La Duchessa torno libera.', 'A Duquesa voltou livre.', 'libera concorda com Duchessa.'),
    ('Parlava sempre di morale.', 'Falava sempre de moral.', 'parlare di significa falar sobre.'),
    ('Trova la morale in tutto.', 'Encontra moral em tudo.', 'in tutto significa em tudo.'),
    ('Alice non rispose subito.', 'Alice não respondeu imediatamente.', 'subito significa imediatamente.'),
    ('La Regina mando via la Duchessa.', 'A Rainha mandou embora a Duquesa.', 'mandare via significa mandar embora.'),
    ('Alice segui il Grifone.', 'Alice seguiu o Grifo.', 'seguire significa seguir.'),
    ('Il Grifone la porto dalla Finta Tartaruga.', 'O Grifo a levou ate a Falsa Tartaruga.', 'portare da qualcuno e levar ate alguém.'),
    ('La Finta Tartaruga sospirava.', 'A Falsa Tartaruga suspirava.', 'sospirare significa suspirar.'),
    ('Racconto la sua scuola.', 'Contou sobre sua escola.', 'raccontare qualcosa significa contar algo.'),
    ('Studiava molte materie strane.', 'Estudava muitas matérias estranhas.', 'materie significa matérias escolares.'),
    ('Alice ascolto con pazienza.', 'Alice escutou com paciencia.', 'con pazienza indica modo paciente.'),
    ('Poi ballarono una quadriglia.', 'Depois dancaram uma quadrilha.', 'ballare significa dançar.'),
    ('La canzone era molto strana.', 'A canção era muito estranha.', 'canzone significa canção.'),
    ('Arrivo un richiamo al processo.', 'Chegou uma chamada para o julgamento.', 'processo significa julgamento.'),
    ('Tutti corsero al tribunale.', 'Todos correram ao tribunal.', 'tribunale significa tribunal.'),
    ('Il Re era il giudice.', 'O Rei era o juiz.', 'giudice significa juiz.'),
    ('La Regina sedeva accanto a lui.', 'A Rainha sentava-se ao lado dele.', 'accanto a significa ao lado de.'),
    ('Il Fante era accusato.', 'O Valete era acusado.', 'accusato significa acusado.'),
    ('Aveva rubato le crostate.', 'Tinha roubado as tortas.', 'rubare significa roubar.'),
    ('Il Cappellaio fu chiamato.', 'O Chapeleiro foi chamado.', 'fu chiamato e voz passiva no passado remoto.'),
    ('Aveva ancora il te in mano.', 'Ainda tinha o chá na mao.', 'in mano significa na mao.'),
    ('Alice cresceva di nuovo.', 'Alice crescia de novo.', 'cresceva mostra processo no passado.'),
    ('Non aveva piu paura.', 'Não tinha mais medo.', 'non piu significa não mais.'),
    ('Le carte volarono in aria.', 'As cartas voaram pelo ar.', 'in aria significa no ar.'),
    ('Alice si sveglio sulla riva.', 'Alice acordou na margem.', 'svegliarsi e acordar.'),
    ('La sorella era accanto a lei.', 'A irmã estava ao lado dela.', 'accanto a lei significa ao lado dela.'),
    ('Era stato tutto un sogno.', 'Tudo tinha sido um sonho.', 'era stato e mais-que-perfeito de essere.'),
    ('Alice racconto la sua avventura.', 'Alice contou sua aventura.', 'avventura significa aventura.'),
    ('La sorella sorrise piano.', 'A irmã sorriu suavemente.', 'sorridere significa sorrir.'),
    ('Alice corse a casa per il te.', 'Alice correu para casa para o chá.', 'per il te indica finalidade ou destino.'),
    ('Alice apri gli occhi lentamente.', 'Alice abriu os olhos lentamente.', 'aprire gli occhi significa abrir os olhos.'),
    ('Il sole stava tramontando.', 'O sol estava se pondo.', 'stare + gerúndio indica ação em andamento.'),
    ('La sorella chiuse il libro.', 'A irmã fechou o livro.', 'chiudere significa fechar.'),
    ('Il prato era tranquillo.', 'O gramado estava tranquilo.', 'prato significa gramado ou campo relvado.'),
    ('Il vento muoveva le foglie.', 'O vento movia as folhas.', 'muoveva é imperfeito de muovere.'),
    ('Alice ricordava il sogno.', 'Alice se lembrava do sonho.', 'ricordare pode ser lembrar; ricordarsi e lembrar-se.'),
    ('Tutto sembrava ancora vero.', 'Tudo ainda parecia real.', 'ancora aqui significa ainda.'),
    ('La voce del Coniglio tornava in mente.', 'A voz do Coelho voltava à mente.', 'tornare in mente significa vir à mente.'),
    ('Il giardino le pareva vicino.', 'O jardim lhe parecia perto.', 'le pareva significa parecia a ela.'),
    ('Le carte danzavano nel ricordo.', 'As cartas dancavam na lembranca.', 'nel ricordo significa na lembranca.'),
    ('Alice rise da sola.', 'Alice riu sozinha.', 'ridere no passado remoto fica rise.'),
    ('Che sogno strano!', 'Que sonho estranho!', 'che antes de substantivo cria exclamação.'),
    ('La sorella ascolto con dolcezza.', 'A irmã escutou com doçura.', 'con dolcezza indica modo suave.'),
    ('Alice parlo velocemente.', 'Alice falou rapidamente.', 'velocemente e advérbio de modo.'),
    ('Racconto del Coniglio Bianco.', 'Contou sobre o Coelho Branco.', 'raccontare di significa contar sobre.'),
    ('Racconto della piccola porta.', 'Contou sobre a pequena porta.', 'della combina di + la.'),
    ('Racconto del giardino luminoso.', 'Contou sobre o jardim luminoso.', 'luminoso significa cheio de luz.'),
    ('Racconto della Regina cattiva.', 'Contou sobre a Rainha malvada.', 'cattiva concorda com Regina.'),
    ('La sorella immagino tutto.', 'A irmã imaginou tudo.', 'immaginare significa imaginar.'),
    ('Anche lei vide il paese meraviglioso.', 'Ela também viu o país maravilhoso.', 'anche lei significa ela também.'),
    ('Ma lo vide nella fantasia.', 'Mas o viu na imaginação.', 'lo vide retoma o país ou sonho.'),
    ('Il rumore del te sembrava vicino.', 'O som do chá parecia perto.', 'rumore pode ser som ou barulho.'),
    ('Il Cappellaio rideva nel sogno.', 'O Chapeleiro ria no sonho.', 'rideva é imperfeito de ridere.'),
    ('La Lepre parlava senza fermarsi.', 'A Lebre falava sem parar.', 'senza fermarsi significa sem parar.'),
    ('Il Ghiro dormiva profondamente.', 'O Leirao dormia profundamente.', 'profondamente intensifica dormir.'),
    ('Il Gatto sorrideva nell aria.', 'O Gato sorria no ar.', 'nell aria combina in + l aria.'),
    ('La Duchessa cercava morali.', 'A Duquesa procurava morais.', 'cercare significa procurar.'),
    ('La cuoca aggiungeva pepe.', 'A cozinheira acrescentava pimenta.', 'aggiungere significa acrescentar.'),
    ('Il bambino diventava maialino.', 'O bebê virava porquinho.', 'diventare indica transformação.'),
    ('Il Bruco restava calmo.', 'A Lagarta permanecia calma.', 'restare significa ficar ou permanecer.'),
    ('Il fumo saliva piano.', 'A fumaca subia devagar.', 'salire significa subir.'),
    ('Il fungo cambiava tutto.', 'O cogumelo mudava tudo.', 'cambiare significa mudar.'),
    ('Un lato faceva crescere.', 'Um lado fazia crescer.', 'fare + infinitivo indica causar uma ação.'),
    ('Un lato faceva diminuire.', 'Um lado fazia diminuir.', 'diminuire significa diminuir.'),
    ('Alice doveva scegliere.', 'Alice precisava escolher.', 'dovere pode indicar necessidade.'),
    ('Scegliere non era facile.', 'Escolher não era fácil.', 'scegliere significa escolher.'),
    ('La curiosita la spingeva avanti.', 'A curiosidade a empurrava para frente.', 'spingere avanti significa empurrar adiante.'),
    ('La paura la fermava poco.', 'O medo a parava pouco.', 'fermare significa parar.'),
    ('Ogni porta prometteva qualcosa.', 'Cada porta prometia algo.', 'ogni usa singular.'),
    ('Ogni stanza era diversa.', 'Cada sala era diferente.', 'diversa concorda com stanza.'),
    ('Ogni domanda portava confusione.', 'Cada pergunta trazia confusao.', 'portare pode significar trazer.'),
    ('Alice cercava una risposta.', 'Alice procurava uma resposta.', 'risposta significa resposta.'),
    ('A volte trovava solo domande.', 'As vezes encontrava apenas perguntas.', 'a volte significa as vezes.'),
    ('Le parole cambiavano significato.', 'As palavras mudavam de significado.', 'significato significa significado.'),
    ('Le regole cambiavano sempre.', 'As regras mudavam sempre.', 'sempre significa sempre.'),
    ('Nessuno spiegava davvero.', 'Ninguem explicava de verdade.', 'davvero significa de verdade.'),
    ('Tutti parlavano insieme.', 'Todos falavam juntos.', 'insieme significa juntos.'),
    ('Alice cercava ordine.', 'Alice procurava ordem.', 'ordine significa ordem.'),
    ('Il paese amava il disordine.', 'O país amava a desordem.', 'disordine é o contrario de ordine.'),
    ('Una domanda tirava l altra.', 'Uma pergunta puxava a outra.', 'tirare pode ser puxar.'),
    ('Una risposta spariva subito.', 'Uma resposta desaparecia logo.', 'sparire significa desaparecer.'),
    ('Il tempo correva strano.', 'O tempo corria estranho.', 'correre pode ser usado para o tempo passar.'),
    ('Le ore non obbedivano.', 'As horas não obedeciam.', 'obbedire significa obedecer.'),
    ('Il sogno mescolava tutto.', 'O sonho misturava tudo.', 'mescolare significa misturar.'),
    ('Alice imparava senza accorgersene.', 'Alice aprendia sem perceber.', 'accorgersi significa perceber.'),
    ('Ogni errore diventava lezione.', 'Cada erro virava licao.', 'diventare indica virar/tornar-se.'),
    ('Ogni paura diventava gioco.', 'Cada medo virava jogo.', 'gioco significa jogo ou brincadeira.'),
    ('Ogni incontro portava parole nuove.', 'Cada encontro trazia palavras novas.', 'parole nuove significa palavras novas.'),
    ('La bambina osservava tutto.', 'A menina observava tudo.', 'osservare significa observar.'),
    ('Non capiva sempre.', 'Não entendia sempre.', 'capire significa entender.'),
    ('Ma continuava a provare.', 'Mas continuava tentando.', 'continuare a + infinitivo indica persistencia.'),
    ('Provare era importante.', 'Tentar era importante.', 'provare significa tentar ou experimentar.'),
    ('Sbagliare non era la fine.', 'Errar não era o fim.', 'sbagliare significa errar.'),
    ('Ricordare richiedeva tempo.', 'Lembrar exigia tempo.', 'richiedere significa exigir/requerer.'),
    ('Ripetere aiutava la memoria.', 'Repetir ajudava a memória.', 'aiutare significa ajudar.'),
    ('Ascoltare aiutava la pronuncia.', 'Escutar ajudava a pronuncia.', 'pronuncia significa pronuncia.'),
    ('Parlare ad alta voce aiutava.', 'Falar em voz alta ajudava.', 'ad alta voce significa em voz alta.'),
    ('Alice ripeteva una frase.', 'Alice repetia uma frase.', 'ripetere significa repetir.'),
    ('Poi la diceva piu piano.', 'Depois a dizia mais devagar.', 'piu piano pode significar mais devagar.'),
    ('Poi la diceva piu forte.', 'Depois a dizia mais alto.', 'piu forte significa mais forte/alto.'),
    ('La frase diventava familiare.', 'A frase se tornava familiar.', 'familiare significa familiar.'),
    ('Una parola tornava spesso.', 'Uma palavra voltava frequentemente.', 'spesso significa frequentemente.'),
    ('Una parola nuova faceva paura.', 'Uma palavra nova dava medo.', 'fare paura significa dar medo.'),
    ('Dopo un po sembrava facile.', 'Depois de um tempo parecia fácil.', 'dopo un po significa depois de um pouco/tempo.'),
    ('La memoria cresceva lentamente.', 'A memória crescia lentamente.', 'lentamente e advérbio de modo.'),
    ('Il ricordo tornava al momento giusto.', 'A lembranca voltava no momento certo.', 'momento giusto significa momento certo.'),
    ('Alice sorrideva soddisfatta.', 'Alice sorria satisfeita.', 'soddisfatta concorda com Alice.'),
    ('Aveva imparato qualcosa.', 'Tinha aprendido algo.', 'imparare significa aprender.'),
    ('Non voleva dimenticare.', 'Não queria esquecer.', 'dimenticare significa esquecer.'),
    ('Per questo ripeteva ancora.', 'Por isso repetia de novo.', 'per questo significa por isso.'),
    ('Una frase al giorno aiutava.', 'Uma frase por dia ajudava.', 'al giorno significa por dia.'),
    ('Venti frasi erano tante.', 'Vinte frases eram muitas.', 'tante concorda com frasi.'),
    ('Troppe frasi stancavano.', 'Frases demais cansavam.', 'troppe indica excesso no feminino plural.'),
    ('Le revisioni tornavano domani.', 'As revisões voltavam amanhã.', 'domani significa amanhã.'),
    ('Alice doveva riposare.', 'Alice precisava descansar.', 'riposare significa descansar.'),
    ('Domani avrebbe ricordato meglio.', 'Amanha lembraria melhor.', 'avrebbe ricordato é condicional composto.'),
    ('Il giorno dopo riprese lo studio.', 'No dia seguinte retomou o estudo.', 'riprendere significa retomar.'),
    ('Prima ascolto la frase.', 'Primeiro escutou a frase.', 'prima pode significar primeiro.'),
    ('Poi provo a ripeterla.', 'Depois tentou repeti-la.', 'ripeterla junta ripetere + la.'),
    ('Poi guardo il testo.', 'Depois olhou o texto.', 'testo significa texto.'),
    ('Infine controllo la traduzione.', 'Por fim conferiu a tradução.', 'infine significa por fim.'),
    ('Questo metodo funzionava.', 'Esse método funcionava.', 'funzionare significa funcionar.'),
    ('La voce guidava l orecchio.', 'A voz guiava o ouvido.', 'orecchio significa ouvido.'),
    ('Il testo guidava gli occhi.', 'O texto guiava os olhos.', 'occhi significa olhos.'),
    ('La traduzione guidava il senso.', 'A tradução guiava o sentido.', 'senso significa sentido.'),
    ('La ripetizione fissava tutto.', 'A repeticao fixava tudo.', 'fissare pode significar fixar.'),
    ('Alice studiava con calma.', 'Alice estudava com calma.', 'con calma significa calmamente.'),
    ('Non correva piu troppo.', 'Não corria mais demais.', 'non piu significa não mais.'),
    ('Sceglieva poche frasi nuove.', 'Escolhia poucas frases novas.', 'poche concorda com frasi.'),
    ('Rivedeva molte frasi vecchie.', 'Revia muitas frases antigas.', 'rivedere significa rever.'),
    ('Cosi ricordava piu a lungo.', 'Assim lembrava por mais tempo.', 'piu a lungo significa por mais tempo.'),
    ('La sorella approvo il piano.', 'A irmã aprovou o plano.', 'approvare significa aprovar.'),
    ('Un buon piano evita confusione.', 'Um bom plano evita confusao.', 'evitare significa evitar.'),
    ('Alice annui contenta.', 'Alice assentiu contente.', 'annuire significa assentir.'),
    ('Il quaderno era pronto.', 'O caderno estava pronto.', 'quaderno significa caderno.'),
    ('La matita era sul tavolo.', 'O lapis estava sobre a mesa.', 'matita significa lapis.'),
    ('Scrisse la prima frase.', 'Escreveu a primeira frase.', 'scrivere no passado remoto fica scrisse.'),
    ('La lesse tre volte.', 'Leu-a três vezes.', 'la lesse retoma a frase.'),
    ('La ripete senza guardare.', 'Repetiu-a sem olhar.', 'senza guardare significa sem olhar.'),
    ('Poi passo alla frase seguente.', 'Depois passou para a frase seguinte.', 'seguente significa seguinte.'),
    ('Il ritmo era semplice.', 'O ritmo era simples.', 'semplice significa simples.'),
    ('Ascolta, ripeti, ricorda.', 'Escute, repita, lembre.', 'sao três imperativos para rotina de estudo.'),
    ('Alice seguiva il ritmo.', 'Alice seguia o ritmo.', 'seguire significa seguir.'),
    ('La lingua sembrava meno lontana.', 'A língua parecia menos distante.', 'meno significa menos.'),
    ('Le frasi aprivano una porta.', 'As frases abriam uma porta.', 'aprire una porta também funciona como metáfora.'),
    ('Dietro la porta c era l italiano.', 'Atras da porta havia o italiano.', 'dietro la porta significa atrás da porta.'),
    ('Alice cadde in una pozza di lacrime.', 'Alice caiu em uma poça de lágrimas.', 'pozza di lacrime significa poça de lágrimas.'),
    ('La pozza era molto salata.', 'A poça era muito salgada.', 'salata concorda com pozza, feminino singular.'),
    ('Un topo nuotava vicino a lei.', 'Um rato nadava perto dela.', 'nuotare significa nadar.'),
    ('Alice provo a parlare con il topo.', 'Alice tentou falar com o rato.', 'provare a + infinitivo indica tentar fazer algo.'),
    ('Il topo non amava i gatti.', 'O rato não gostava de gatos.', 'amare aqui expressa gostar de algo.'),
    ('Alice capi di aver sbagliato argomento.', 'Alice entendeu que tinha errado o assunto.', 'aver sbagliato usa avere + participio.'),
    ('Gli animali uscirono dall acqua.', 'Os animais sairam da água.', 'uscire da indica sair de algum lugar.'),
    ('Tutti erano bagnati e confusi.', 'Todos estavam molhados e confusos.', 'bagnati e confusi concordam com tutti.'),
    ('Il Dodo propose una corsa.', 'O Dodo propos uma corrida.', 'proporre no passado remoto fica propose.'),
    ('Nessuno sapeva dove cominciare.', 'Ninguem sabia onde começar.', 'nessuno pede verbo no singular.'),
    ('Alla fine tutti vinsero.', 'No fim todos venceram.', 'alla fine significa no fim.'),
    ('Alice distribui piccoli premi.', 'Alice distribuiu pequenos prêmios.', 'distribui é passado remoto de distribuire.'),
    ('Poi trovo una casetta bianca.', 'Depois encontrou uma casinha branca.', 'casetta é diminutivo de casa.'),
    ('Il Coniglio cercava i guanti.', 'O Coelho procurava as luvas.', 'cercare significa procurar.'),
    ('Alice entro nella casetta.', 'Alice entrou na casinha.', 'entrare in significa entrar em.'),
    ('Bevve da una piccola bottiglia.', 'Bebeu de uma pequena garrafa.', 'bevve é passado remoto de bere.'),
    ('Subito divento enorme.', 'Imediatamente ficou enorme.', 'diventare significa tornar-se ou ficar.'),
    ('Il braccio usci dalla finestra.', 'O braço saiu pela janela.', 'uscire dalla finestra significa sair pela janela.'),
    ('Il Coniglio si spavento molto.', 'O Coelho se assustou muito.', 'spaventarsi significa assustar-se.'),
    ('Una folla si raduno fuori.', 'Uma multidao se reuniu do lado de fora.', 'radunarsi significa reunir-se.'),
    ('Alice mangio un piccolo dolce.', 'Alice comeu um pequeno doce.', 'dolce pode significar doce ou sobremesa.'),
    ('Finalmente torno piccola.', 'Finalmente voltou a ficar pequena.', 'tornare + adjetivo indica voltar a um estado.'),
    ('Nel bosco incontro un bruco.', 'No bosque encontrou uma lagarta.', 'bruco significa lagarta.'),
    ('Il Bruco fumava tranquillo.', 'A Lagarta fumava tranquila.', 'tranquillo descreve o modo calmo da cena.'),
    ('Chi sei tu?', 'Quem é você?', 'chi sei tu é uma pergunta direta de identidade.'),
    ('Alice non sapeva rispondere.', 'Alice não sabia responder.', 'sapere + infinitivo indica saber fazer algo.'),
    ('Era cambiata tante volte.', 'Ela tinha mudado muitas vezes.', 'era cambiata usa essere + participio.'),
    ('Il Bruco le diede un consiglio.', 'A Lagarta lhe deu um conselho.', 'le significa a ela.'),
    ('Un lato del fungo la faceva crescere.', 'Um lado do cogumelo a fazia crescer.', 'fungo significa cogumelo.'),
    ('L altro lato la faceva rimpicciolire.', 'O outro lado a fazia diminuir.', 'rimpicciolire significa ficar menor.'),
    ('Alice prese due pezzi di fungo.', 'Alice pegou dois pedacos de cogumelo.', 'pezzi di fungo significa pedacos de cogumelo.'),
    ('Alice cammino tra gli alberi alti.', 'Alice caminhou entre as árvores altas.', 'tra significa entre; alberi alti concorda no masculino plural.'),
    ('Un ramo le sfioro il viso.', 'Um galho tocou de leve seu rosto.', 'sfiorare significa tocar de leve.'),
    ('Sentiva un profumo strano nell aria.', 'Sentia um cheiro estranho no ar.', 'nell aria combina in + l aria.'),
    ('Davanti apparve una piccola casa.', 'Adiante apareceu uma pequena casa.', 'apparire no passado remoto fica apparve.'),
    ('La casa aveva un tetto basso.', 'A casa tinha um teto baixo.', 'tetto basso descreve um teto baixo.'),
    ('Un pesce vestito bussava alla porta.', 'Um peixe vestido batia na porta.', 'bussare alla porta significa bater na porta.'),
    ('Un servo rana apri lentamente.', 'Um criado sapo abriu lentamente.', 'servo indica criado; rana significa sapo ou ra.'),
    ('I due servi parlavano in modo solenne.', 'Os dois criados falavam de modo solene.', 'in modo solenne indica maneira formal.'),
    ('Alice ascolto senza capire tutto.', 'Alice escutou sem entender tudo.', 'senza + infinitivo significa sem fazer algo.'),
    ('La lettera era per la Duchessa.', 'A carta era para a Duquesa.', 'per indica destinatario.'),
    ('Il servo la consegno con un inchino.', 'O criado a entregou com uma reverencia.', 'la retoma lettera; inchino significa reverencia.'),
    ('Dentro la casa regnava confusione.', 'Dentro da casa reinava confusao.', 'regnare pode significar reinar ou dominar.'),
    ('La cucina era piena di fumo.', 'A cozinha estava cheia de fumaca.', 'piena di significa cheia de.'),
    ('La cuoca agitava una grande pentola.', 'A cozinheira mexia uma grande panela.', 'agitare indica mover ou sacudir.'),
    ('Il pepe faceva starnutire tutti.', 'A pimenta fazia todos espirrarem.', 'fare + infinitivo indica fazer alguém realizar uma ação.'),
    ('La Duchessa teneva un bambino.', 'A Duquesa segurava um bebê.', 'tenere significa segurar ou manter.'),
    ('Il bambino piangeva fortissimo.', 'O bebê chorava muito forte.', 'fortissimo intensifica a ação.'),
    ('Alice tossi per il fumo.', 'Alice tossiu por causa da fumaca.', 'per il fumo indica causa.'),
    ('La cuoca lancio un piatto.', 'A cozinheira lancou um prato.', 'lanciare significa lancar ou jogar.'),
    ('Il piatto volo vicino ad Alice.', 'O prato voou perto de Alice.', 'volare no passado remoto fica volo.'),
    ('Alice penso che fosse pericoloso.', 'Alice pensou que fosse perigoso.', 'fosse e subjuntivo imperfeito de essere.'),
    ('La Duchessa parlava con voce aspra.', 'A Duquesa falava com voz áspera.', 'voce aspra indica um tom duro.'),
    ('Ogni frase sembrava una morale.', 'Cada frase parecia uma moral.', 'ogni fica no singular mesmo com sentido de cada.'),
    ('Alice non amava quelle morali.', 'Alice não gostava daquelas morais.', 'quelle concorda com morali no feminino plural.'),
    ('Il gatto sorrideva sopra il focolare.', 'O gato sorria sobre a lareira.', 'focolare significa lareira ou fogo domestico.'),
    ('Quel sorriso era davvero largo.', 'Aquele sorriso era realmente largo.', 'davvero reforça a ideia de realmente.'),
    ('Alice guardo il Gatto con cautela.', 'Alice olhou o Gato com cautela.', 'con cautela significa cuidadosamente.'),
    ('Il Gatto sembrava sapere molte cose.', 'O Gato parecia saber muitas coisas.', 'sembrare + infinitivo indica parecer fazer algo.'),
    ('La Duchessa affido il bambino ad Alice.', 'A Duquesa confiou o bebê a Alice.', 'affidare qualcosa a qualcuno significa confiar algo a alguém.'),
    ('Alice usci in fretta dalla casa.', 'Alice saiu rapidamente da casa.', 'uscire da indica sair de um lugar.'),
    ('Il bambino grugni come un maialino.', 'O bebê grunhiu como um porquinho.', 'grugnire descreve som de porco.'),
    ('Alice lo guardo sorpresa.', 'Alice o olhou surpresa.', 'lo retoma bambino.'),
    ('Il volto del bambino cambio.', 'O rosto do bebê mudou.', 'volto significa rosto.'),
    ('Il naso divento piu schiacciato.', 'O nariz ficou mais achatado.', 'schiacciato significa achatado.'),
    ('Alla fine era un maiale.', 'No fim era um porco.', 'alla fine marca conclusão.'),
    ('Alice lascio andare il maialino.', 'Alice deixou o porquinho ir.', 'lasciare andare significa soltar ou deixar ir.'),
    ('Il Gatto apparve su un ramo.', 'O Gato apareceu em um galho.', 'su un ramo significa em/sobre um galho.'),
    ('Solo il sorriso arrivo per primo.', 'So o sorriso chegou primeiro.', 'per primo significa em primeiro lugar.'),
    ('Alice chiese quale strada prendere.', 'Alice perguntou qual caminho tomar.', 'quale strada significa qual caminho.'),
    ('Il Gatto rispose con calma.', 'O Gato respondeu com calma.', 'rispondere no passado remoto fica rispose.'),
    ('Dipende da dove vuoi andare.', 'Depende de onde você quer ir.', 'dipendere da significa depender de.'),
    ('Alice non aveva una meta precisa.', 'Alice não tinha uma meta precisa.', 'meta precisa significa destino claro.'),
    ('Allora ogni strada puo andare bene.', 'Então qualquer caminho pode servir.', 'puo andare bene significa pode estar bom/servir.'),
    ('Il Cappellaio viveva da una parte.', 'O Chapeleiro vivia de um lado.', 'da una parte indica um lado.'),
    ('La Lepre viveva dall altra parte.', 'A Lebre vivia do outro lado.', 'dall altra parte significa do outro lado.'),
    ('Entrambi erano un po matti.', 'Ambos eram um pouco loucos.', 'entrambi significa ambos.'),
    ('Il Gatto svani lentamente.', 'O Gato desapareceu lentamente.', 'svanire significa desaparecer.'),
    ('Rimase soltanto il sorriso.', 'Restou somente o sorriso.', 'rimanere no passado remoto fica rimase.'),
    ('Alice trovo una tavola apparecchiata.', 'Alice encontrou uma mesa posta.', 'tavola apparecchiata significa mesa posta.'),
    ('La tavola era sotto un albero.', 'A mesa estava sob uma árvore.', 'sotto indica posição abaixo.'),
    ('Il Cappellaio beveva il te.', 'O Chapeleiro bebia chá.', 'te significa chá.'),
    ('La Lepre offriva altro te.', 'A Lebre oferecia mais chá.', 'altro te significa mais chá.'),
    ('Il Ghiro dormiva tra loro.', 'O Dormidongo dormia entre eles.', 'tra loro significa entre eles.'),
    ('Non c era posto per Alice.', 'Não havia lugar para Alice.', 'posto significa lugar ou assento.'),
    ('Alice si sedette comunque.', 'Alice se sentou mesmo assim.', 'comunque pode significar mesmo assim.'),
    ('Il Cappellaio fece una domanda strana.', 'O Chapeleiro fez uma pergunta estranha.', 'fare una domanda significa fazer uma pergunta.'),
    ('La domanda non aveva risposta.', 'A pergunta não tinha resposta.', 'risposta significa resposta.'),
    ('Alice provo a indovinare.', 'Alice tentou adivinhar.', 'indovinare significa adivinhar.'),
    ('La Lepre cambio argomento.', 'A Lebre mudou de assunto.', 'cambiare argomento significa mudar de assunto.'),
    ('Il tempo era fermo per loro.', 'O tempo estava parado para eles.', 'fermo significa parado.'),
    ('Erano sempre all ora del te.', 'Estavam sempre na hora do chá.', 'all ora del te significa na hora do chá.'),
    ('Le tazze giravano intorno al tavolo.', 'As xicaras giravam ao redor da mesa.', 'girare intorno significa girar ao redor.'),
    ('Alice trovava tutto assurdo.', 'Alice achava tudo absurdo.', 'trovare pode significar achar ou considerar.'),
    ('Il Ghiro racconto una storia.', 'O Dormidongo contou uma história.', 'raccontare una storia significa contar uma história.'),
    ('La storia parlava di tre sorelle.', 'A história falava de três irmãs.', 'parlare di significa falar de.'),
    ('Le sorelle vivevano in un pozzo.', 'As irmãs viviam em um poco.', 'pozzo significa poco.'),
    ('Alice fece troppe domande.', 'Alice fez perguntas demais.', 'troppe concorda com domande.'),
    ('Gli altri si irritarono subito.', 'Os outros se irritaram imediatamente.', 'irritarsi significa irritar-se.'),
    ('Alice si alzo offesa.', 'Alice se levantou ofendida.', 'alzarsi significa levantar-se.'),
    ('Lascio la tavola senza salutare.', 'Deixou a mesa sem cumprimentar.', 'senza salutare significa sem se despedir.'),
    ('Una porta apparve in un albero.', 'Uma porta apareceu em uma árvore.', 'in un albero indica dentro/na árvore.'),
    ('Alice entro di nuovo nella sala.', 'Alice entrou de novo na sala.', 'di nuovo significa novamente.'),
    ('La chiave era ancora sul tavolo.', 'A chave ainda estava sobre a mesa.', 'ancora significa ainda.'),
    ('Questa volta Alice fu prudente.', 'Desta vez Alice foi prudente.', 'questa volta significa desta vez.'),
    ('Prese prima la chiave dorata.', 'Pegou primeiro a chave dourada.', 'prima pode significar antes ou primeiro.'),
    ('Poi mangio il fungo giusto.', 'Depois comeu o cogumelo certo.', 'giusto significa certo ou adequado.'),
    ('Raggiunse finalmente il giardino.', 'Finalmente alcançou o jardim.', 'raggiungere significa alcançar.'),
    ('Il giardino era luminoso e ordinato.', 'O jardim era luminoso e organizado.', 'ordinato significa arrumado ou ordenado.'),
    ('Tre giardinieri dipingevano rose.', 'Tres jardineiros pintavam rosas.', 'dipingere significa pintar.'),
    ('Le rose bianche diventavano rosse.', 'As rosas brancas ficavam vermelhas.', 'diventare rosse significa ficar vermelhas.'),
    ('Alice chiese il motivo.', 'Alice perguntou o motivo.', 'motivo significa razao.'),
    ('I giardinieri avevano paura.', 'Os jardineiros tinham medo.', 'avere paura significa ter medo.'),
    ('La Regina voleva rose rosse.', 'A Rainha queria rosas vermelhas.', 'voleva é imperfeito de volere.'),
    ('Arrivo una grande processione.', 'Chegou uma grande procissao.', 'arrivare no passado remoto fica arrivo.'),
    ('Le carte marciavano in fila.', 'As cartas marchavam em fila.', 'in fila significa em fila.'),
    ('Il Re camminava accanto alla Regina.', 'O Rei caminhava ao lado da Rainha.', 'accanto a significa ao lado de.'),
    ('La Regina aveva un tono terribile.', 'A Rainha tinha um tom terrivel.', 'tono terribile indica maneira assustadora de falar.'),
    ('Tagliategli la testa!', 'Cortem-lhe a cabeça!', 'tagliategli junta tagliare + gli.'),
    ('Alice non si spavento subito.', 'Alice não se assustou imediatamente.', 'subito pode significar imediatamente.'),
    ('Le carte erano solo carte.', 'As cartas eram apenas cartas.', 'solo aqui significa apenas.'),
    ('La Regina invito Alice a giocare.', 'A Rainha convidou Alice para jogar.', 'invitare a + infinitivo significa convidar para fazer algo.'),
    ('Il croquet era molto strano.', 'O croque era muito estranho.', 'croquet em italiano pode aparecer como croquet/croche.'),
    ('I fenicotteri servivano da mazze.', 'Os flamingos serviam de tacos.', 'servire da significa servir como.'),
    ('I ricci facevano da palle.', 'Os ouricos faziam o papel de bolas.', 'fare da significa agir como.'),
    ('I soldati piegati formavano archi.', 'Os soldados curvados formavam arcos.', 'piegati significa dobrados ou curvados.'),
    ('Tutto si muoveva continuamente.', 'Tudo se movia continuamente.', 'continuamente indica ação repetida.'),
    ('Alice non riusciva a colpire bene.', 'Alice não conseguia bater bem.', 'riuscire a + infinitivo indica conseguir.'),
    ('La Regina gridava a ogni momento.', 'A Rainha gritava a cada momento.', 'a ogni momento significa o tempo todo.'),
    ('Il Gatto apparve durante la partita.', 'O Gato apareceu durante a partida.', 'durante indica simultaneidade.'),
    ('Apparve solo la testa del Gatto.', 'Apareceu apenas a cabeça do Gato.', 'solo la testa significa apenas a cabeça.'),
    ('Il Re non sapeva cosa fare.', 'O Rei não sabia o que fazer.', 'cosa fare significa o que fazer.'),
    ('La Regina voleva tagliarla via.', 'A Rainha queria cortá-la fora.', 'tagliarla junta tagliare + la.'),
    ('Nessuno trovava il corpo.', 'Ninguem encontrava o corpo.', 'corpo significa corpo.'),
    ('Senza corpo era difficile procedere.', 'Sem corpo era difícil prosseguir.', 'procedere significa prosseguir.'),
    ('La Duchessa torno nel giardino.', 'A Duquesa voltou ao jardim.', 'tornare in/nel indica voltar a um lugar.'),
    ('Sembrava piu gentile di prima.', 'Parecia mais gentil do que antes.', 'piu gentile di prima compara dois momentos.'),
    ('Camminava stretta al braccio di Alice.', 'Caminhava agarrada ao braço de Alice.', 'al braccio indica contato com o braço.'),
    ('Trovava morali in ogni cosa.', 'Encontrava morais em cada coisa.', 'in ogni cosa significa em tudo.'),
    ('Alice ascoltava con pazienza.', 'Alice escutava com paciencia.', 'con pazienza indica modo paciente.'),
    ('La Regina la mando via.', 'A Rainha a mandou embora.', 'mandare via significa mandar embora.'),
    ('Poi arrivo il Grifone.', 'Depois chegou o Grifo.', 'grifone significa grifo, criatura mitológica.'),
    ('Il Grifone porto Alice lontano.', 'O Grifo levou Alice para longe.', 'portare lontano significa levar para longe.'),
    ('Dovevano incontrare la Finta Tartaruga.', 'Deviam encontrar a Tartaruga Falsa.', 'dovere + infinitivo indica dever ou precisar.'),
    ('La Finta Tartaruga era molto triste.', 'A Tartaruga Falsa estava muito triste.', 'finta significa falsa ou fingida.'),
    ('Sospirava tra una frase e l altra.', 'Suspirava entre uma frase e outra.', 'tra una frase e l altra indica intervalo.'),
    ('Racconto la sua vecchia scuola.', 'Contou sobre sua antiga escola.', 'vecchia scuola significa antiga escola.'),
    ('Studiava in fondo al mare.', 'Estudava no fundo do mar.', 'in fondo al mare significa no fundo do mar.'),
    ('Il maestro era una vera tartaruga.', 'O professor era uma tartaruga de verdade.', 'vera significa verdadeira.'),
    ('Le lezioni diminuivano ogni giorno.', 'As aulas diminuiam a cada dia.', 'diminuire significa diminuir.'),
    ('Alice trovo strana quella scuola.', 'Alice achou estranha aquela escola.', 'quella scuola significa aquela escola.'),
    ('La Tartaruga parlo di molte materie.', 'A Tartaruga falou de muitas matérias.', 'materie significa matérias escolares.'),
    ('C era lettura e scrittura.', 'Havia leitura e escrita.', 'lettura e scrittura sao substantivos de estudo.'),
    ('C era anche il far di conto.', 'Havia também fazer contas.', 'far di conto significa calcular.'),
    ('Il Grifone rideva piano.', 'O Grifo ria baixinho.', 'ridere piano significa rir baixo.'),
    ('Alice cercava di essere educata.', 'Alice tentava ser educada.', 'cercare di + infinitivo significa tentar.'),
    ('Poi parlarono di una danza.', 'Depois falaram de uma dança.', 'parlare di introduce o assunto.'),
    ('La danza si chiamava Quadriglia.', 'A dança se chamava Quadrilha.', 'chiamarsi significa chamar-se.'),
    ('Bisognava ballare con aragoste.', 'Era preciso dançar com lagostas.', 'bisognava indica necessidade impessoal no passado.'),
    ('Alice non conosceva quella danza.', 'Alice não conhecia aquela dança.', 'conoscere significa conhecer.'),
    ('La Tartaruga canto una canzone.', 'A Tartaruga cantou uma canção.', 'cantare una canzone significa cantar uma canção.'),
    ('La canzone era lenta e triste.', 'A canção era lenta e triste.', 'lenta e triste concordam com canzone.'),
    ('Alice penso alla sua scuola.', 'Alice pensou em sua escola.', 'pensare a significa pensar em.'),
    ('Il Grifone la interruppe.', 'O Grifo a interrompeu.', 'interrompere no passado remoto fica interruppe.'),
    ('Si udi un grido lontano.', 'Ouviu-se um grito distante.', 'si udi é forma impessoal/passiva: ouviu-se.'),
    ('Il processo stava per cominciare.', 'O julgamento estava para começar.', 'stare per + infinitivo indica ação iminente.'),
    ('Alice corse verso il tribunale.', 'Alice correu em direção ao tribunal.', 'verso indica direção.'),
    ('La sala era piena di animali.', 'A sala estava cheia de animais.', 'piena di significa cheia de.'),
    ('Il Re sedeva come giudice.', 'O Rei estava sentado como juiz.', 'sedere no imperfeito fica sedeva.'),
    ('La Regina sedeva accanto a lui.', 'A Rainha estava sentada ao lado dele.', 'accanto a lui significa ao lado dele.'),
    ('Il Coniglio leggeva l accusa.', 'O Coelho lia a acusação.', 'accusa significa acusação.'),
    ('Il Fante era sotto processo.', 'O Valete estava sendo julgado.', 'essere sotto processo significa estar sob julgamento.'),
    ('Aveva rubato le crostate.', 'Tinha roubado as tortas.', 'rubare significa roubar.'),
    ('Le crostate erano su un piatto.', 'As tortas estavam em um prato.', 'su un piatto significa em/sobre um prato.'),
    ('Alice guardo le prove con attenzione.', 'Alice olhou as provas com atenção.', 'prove significa provas ou evidências.'),
    ('La giuria scriveva tutto.', 'O júri escrevia tudo.', 'giuria significa júri.'),
    ('Scriveva anche cose inutili.', 'Escrevia também coisas inúteis.', 'anche significa também.'),
    ('Alice cominciava a crescere ancora.', 'Alice começava a crescer novamente.', 'cominciare a indica início de ação.'),
    ('Il primo testimone fu il Cappellaio.', 'A primeira testemunha foi o Chapeleiro.', 'testimone significa testemunha.'),
    ('Portava ancora una tazza di te.', 'Ainda carregava uma xícara de chá.', 'portare significa carregar ou levar.'),
    ('Tremava davanti al Re.', 'Tremia diante do Rei.', 'davanti a significa diante de.'),
    ('Il Re gli fece molte domande.', 'O Rei lhe fez muitas perguntas.', 'gli significa a ele.'),
    ('Il Cappellaio rispose confuso.', 'O Chapeleiro respondeu confuso.', 'confuso descreve o estado do sujeito.'),
    ('La Regina voleva punirlo subito.', 'A Rainha queria puni-lo imediatamente.', 'punirlo junta punire + lo.'),
    ('Poi entro la cuoca.', 'Depois entrou a cozinheira.', 'entrare no passado remoto fica entro.'),
    ('La cuoca parlava poco.', 'A cozinheira falava pouco.', 'poco modifica a quantidade.'),
    ('Disse solo pepe.', 'Disse apenas pimenta.', 'solo significa apenas.'),
    ('Tutti starnutirono di nuovo.', 'Todos espirraram de novo.', 'starnutire significa espirrar.'),
    ('Il Ghiro nego di sapere qualcosa.', 'O Dormidongo negou saber alguma coisa.', 'negare di + infinitivo significa negar fazer/saber algo.'),
    ('Alice cresceva sempre di piu.', 'Alice crescia cada vez mais.', 'sempre di piu significa cada vez mais.'),
    ('Le carte guardavano in alto.', 'As cartas olhavam para cima.', 'in alto indica direção para cima.'),
    ('Il Re chiamo Alice come testimone.', 'O Rei chamou Alice como testemunha.', 'chiamare qualcuno come testimone significa chamar como testemunha.'),
    ('Alice si alzo in piedi.', 'Alice se levantou.', 'alzarsi in piedi significa ficar de pé.'),
    ('Rovescio il banco della giuria.', 'Derrubou a bancada do júri.', 'rovesciare significa virar ou derrubar.'),
    ('I giurati caddero dappertutto.', 'Os jurados cairam por toda parte.', 'dappertutto significa por toda parte.'),
    ('Alice li rimise al posto.', 'Alice os colocou de volta no lugar.', 'li retoma giurati.'),
    ('Il Coniglio lesse una lettera.', 'O Coelho leu uma carta.', 'lesse é passado remoto de leggere.'),
    ('La lettera non aveva firma.', 'A carta não tinha assinatura.', 'firma significa assinatura.'),
    ('Il Re la considero importante.', 'O Rei a considerou importante.', 'considerare significa considerar.'),
    ('Alice non era d accordo.', 'Alice não concordava.', 'essere d accordo significa estar de acordo.'),
    ('La prova non provava nulla.', 'A prova não provava nada.', 'nulla significa nada.'),
    ('Il Re cerco una regola.', 'O Rei procurou uma regra.', 'regola significa regra.'),
    ('La regola era senza senso.', 'A regra era sem sentido.', 'senza senso significa sem sentido.'),
    ('Prima la sentenza, poi il verdetto.', 'Primeiro a sentença, depois o veredito.', 'prima... poi organiza sequência.'),
    ('Alice protesto con decisione.', 'Alice protestou com decisão.', 'con decisione significa firmemente.'),
    ('Il verdetto deve venire prima.', 'O veredito deve vir primeiro.', 'deve venire indica obrigação ou ordem correta.'),
    ('La Regina grido piu forte.', 'A Rainha gritou mais alto.', 'piu forte significa mais forte ou mais alto.'),
    ('Alice non ebbe piu paura.', 'Alice não teve mais medo.', 'non ebbe piu usa passato remoto de avere.'),
    ('Siete soltanto un mazzo di carte.', 'Vocês sao apenas um baralho de cartas.', 'mazzo di carte significa baralho.'),
    ('Le carte volarono contro di lei.', 'As cartas voaram contra ela.', 'contro di lei significa contra ela.'),
    ('Alice agito le mani.', 'Alice agitou as mãos.', 'agitare le mani significa mexer/agitar as mãos.'),
    ('All improvviso si sveglio.', 'De repente ela acordou.', 'svegliarsi significa acordar.'),
    ('Era di nuovo sulla riva.', 'Estava de novo na margem.', 'di nuovo significa novamente.'),
    ('La sorella era accanto a lei.', 'A irmã estava ao lado dela.', 'accanto a lei significa ao lado dela.'),
    ('Le foglie cadevano dagli alberi.', 'As folhas caíam das árvores.', 'cadere dagli alberi significa cair das árvores.'),
    ('Alice racconto il sogno intero.', 'Alice contou o sonho inteiro.', 'raccontare significa contar ou narrar.'),
    ('La sorella ascolto sorridendo.', 'A irmã escutou sorrindo.', 'sorridendo e gerúndio: sorrindo.'),
    ('Il sogno sembrava ancora vivo.', 'O sonho ainda parecia vivo.', 'ancora vivo significa ainda vivo.'),
    ('Alice corse verso casa.', 'Alice correu em direção a casa.', 'verso casa significa em direção a casa.'),
    ('Pensava al te della sera.', 'Pensava no chá da noite.', 'pensare a + artigo vira pensava al.'),
    ('La sorella resto seduta.', 'A irmã permaneceu sentada.', 'restare significa permanecer.'),
    ('Immagino Alice da grande.', 'Imaginou Alice adulta.', 'da grande significa quando adulta.'),
    ('Forse avrebbe ricordato quel paese.', 'Talvez se lembrasse daquele país.', 'avrebbe ricordato é condicional composto.'),
    ('Forse avrebbe raccontato la storia.', 'Talvez contasse a história.', 'raccontare la storia significa contar a história.'),
    ('I bambini avrebbero ascoltato stupiti.', 'As criancas escutariam admiradas.', 'avrebbero ascoltato é condicional composto.'),
    ('Ogni scena sarebbe tornata viva.', 'Cada cena voltaria viva.', 'sarebbe tornata usa essere no condicional composto.'),
    ('Il Coniglio avrebbe corso ancora.', 'O Coelho correria de novo.', 'avrebbe corso significa teria corrido/correria.'),
    ('Il Gatto avrebbe sorriso tra i rami.', 'O Gato sorriria entre os galhos.', 'tra i rami significa entre os galhos.'),
    ('La Regina avrebbe gridato ordini.', 'A Rainha gritaria ordens.', 'avrebbe gridato é condicional composto.'),
    ('Il giardino sarebbe rimasto luminoso.', 'O jardim teria permanecido luminoso.', 'sarebbe rimasto usa essere + participio.'),
    ('Alice avrebbe sorriso ricordando.', 'Alice sorriria lembrando.', 'ricordando e gerúndio: lembrando.'),
    ('La lingua del sogno restava musicale.', 'A língua do sonho permanecia musical.', 'restare significa permanecer.'),
    ('Ogni frase portava un immagine.', 'Cada frase trazia uma imagem.', 'immagine significa imagem.'),
    ('Ogni immagine aiutava la memoria.', 'Cada imagem ajudava a memória.', 'aiutare significa ajudar.'),
    ('Alice poteva studiare con fantasia.', 'Alice podia estudar com fantasia.', 'potere no imperfeito fica poteva.'),
    ('La fantasia rendeva facile ricordare.', 'A fantasia tornava fácil lembrar.', 'rendere + adjetivo significa tornar algo de certo modo.'),
    ('Una scena dava senso alle parole.', 'Uma cena dava sentido as palavras.', 'dare senso a significa dar sentido a.'),
    ('Una parola apriva un altra scena.', 'Uma palavra abria outra cena.', 'un altra concorda com scena.'),
    ('Il viaggio diventava un metodo.', 'A viagem se tornava um método.', 'diventare significa tornar-se.'),
    ('Ascoltare veniva prima di leggere.', 'Escutar vinha antes de ler.', 'venire prima di significa vir antes de.'),
    ('Ripetere veniva prima di tradurre.', 'Repetir vinha antes de traduzir.', 'prima di + infinitivo significa antes de fazer algo.'),
    ('Capire veniva prima di correre.', 'Entender vinha antes de correr.', 'capire significa entender.'),
    ('Alice imparava senza fretta.', 'Alice aprendia sem pressa.', 'senza fretta significa sem pressa.'),
    ('Ogni revisione proteggeva il ricordo.', 'Cada revisão protegia a lembranca.', 'proteggere no imperfeito fica proteggeva.'),
    ('Ogni errore mostrava un punto debole.', 'Cada erro mostrava um ponto fraco.', 'punto debole significa ponto fraco.'),
    ('Ogni acerto dava fiducia.', 'Cada acerto dava confiança.', 'fiducia significa confiança.'),
    ('La storia diventava piu chiara.', 'A história ficava mais clara.', 'piu chiara concorda com storia.'),
    ('Il suono diventava familiare.', 'O som ficava familiar.', 'suono significa som.'),
    ('Il ritmo aiutava la pronuncia.', 'O ritmo ajudava a pronuncia.', 'ritmo significa ritmo.'),
    ('La voce guidava la memoria.', 'A voz guiava a memória.', 'guidare significa guiar.'),
    ('Il testo confermava il significato.', 'O texto confirmava o significado.', 'confermare significa confirmar.'),
    ('La traduzione chiariva i dettagli.', 'A tradução esclarecia os detalhes.', 'chiarire significa esclarecer.'),
    ('Alice sceglieva una nota sincera.', 'Alice escolhia uma nota sincera.', 'scegliere no imperfeito fica sceglieva.'),
    ('Se sbagliava, riprovava presto.', 'Se errava, tentava de novo em breve.', 'se introduz condição.'),
    ('Se ricordava, aspettava piu giorni.', 'Se lembrava, esperava mais dias.', 'aspettare significa esperar.'),
    ('Cosi il tempo lavorava per lei.', 'Assim o tempo trabalhava por ela.', 'lavorare per qualcuno significa trabalhar a favor de alguém.'),
    ('Il paese delle meraviglie restava aperto.', 'O país das maravilhas permanecia aberto.', 'restare aperto significa permanecer aberto.'),
    ('Ogni ritorno era piu semplice.', 'Cada retorno era mais simples.', 'ritorno significa retorno.'),
    ('Ogni frase era una piccola porta.', 'Cada frase era uma pequena porta.', 'piccola porta retoma a imagem da porta.'),
    ('Alice entrava con piu sicurezza.', 'Alice entrava com mais segurança.', 'sicurezza significa segurança ou confiança.'),
    ('Il corso seguiva il suo passo.', 'O curso seguia seu ritmo.', 'passo pode significar ritmo ou passo.'),
    ('La curiosita restava il motore.', 'A curiosidade continuava sendo o motor.', 'motore funciona como metáfora de impulso.'),
    ('Studiare poteva essere un avventura.', 'Estudar podia ser uma aventura.', 'poteva essere significa podia ser.'),
    ('Alice lo capi poco a poco.', 'Alice entendeu isso pouco a pouco.', 'poco a poco significa gradualmente.'),
]


def build_study_note(italian_text, focus):
    return (
        f'Foco da frase: {focus}\n'
        'Como revisar: leia o italiano, cubra a tradução e diga o sentido em voz alta antes de revelar.\n'
        'Depois compare palavra por palavra e escolha a nota pensando na facilidade de lembrar sem olhar.'
    )


def iter_alice_cards(limit=None):
    cards = ALICE_CARDS if limit is None else ALICE_CARDS[:limit]
    for index, (text, translation, focus) in enumerate(cards, start=1):
        yield {
            'deck_key': f'alice-{index:04d}',
            'order': index,
            'italian_text': text,
            'portuguese_text': translation,
            'study_note': build_study_note(text, focus),
        }
