RANDOM_SHORT_SOURCE_TITLE = 'Frases curtas aleatorias em italiano'
RANDOM_SHORT_CHAPTER = 'Frases curtas aleatorias'


RANDOM_SHORT_CARDS = [
    ("Oggi studio italiano con calma.", "Hoje eu estudo italiano com calma.", "Vocabulário: oggi = hoje; studio = eu estudo; con calma = com calma.\nGramática: o presente studio fala de uma ação atual ou planejada para hoje.\nTreino: repita pensando em uma rotina real de estudo, sem traduzir palavra por palavra."),
    ("Domani parlo con il professore.", "Amanhã eu falo com o professor.", "Vocabulário: domani = amanhã; parlo = eu falo; professore = professor.\nGramática: em italiano o presente pode indicar futuro próximo quando há marcador de tempo.\nTreino: troque professore por amico, collega ou cliente."),
    ("Mi piace ascoltare la musica italiana.", "Eu gosto de escutar música italiana.", "Vocabulário: mi piace = eu gosto; ascoltare = escutar; musica italiana = música italiana.\nGramática: depois de mi piace, o infinitivo ascoltare funciona como a coisa de que você gosta.\nTreino: substitua ascoltare por studiare, parlare ou leggere."),
    ("Non capisco questa frase.", "Eu não entendo esta frase.", "Vocabulário: non capisco = não entendo; questa = esta; frase = frase.\nGramática: non vem antes do verbo conjugado.\nTreino: use quando uma frase específica estiver difícil."),
    ("Puoi parlare più piano?", "Você pode falar mais devagar?", "Vocabulário: puoi = você pode; parlare = falar; più piano = mais devagar.\nGramática: puoi + infinitivo forma um pedido direto.\nTreino: fale com entonação de pergunta e destaque più piano."),
    ("Vorrei un caffè, per favore.", "Eu gostaria de um café, por favor.", "Vocabulário: vorrei = eu gostaria; caffè = café; per favore = por favor.\nGramática: vorrei é uma forma educada, melhor que voglio em pedidos.\nTreino: troque caffè por acqua, tè ou panino."),
    ("Prendo l'autobus ogni mattina.", "Eu pego o ônibus toda manhã.", "Vocabulário: prendo = eu pego; autobus = ônibus; ogni mattina = toda manhã.\nGramática: ogni fica no singular mesmo com sentido repetido.\nTreino: use para falar da sua rotina diária."),
    ("Aspetto un messaggio importante.", "Estou esperando uma mensagem importante.", "Vocabulário: aspetto = espero/estou esperando; messaggio = mensagem; importante = importante.\nGramática: o presente italiano pode equivaler ao gerúndio em português.\nTreino: imagine olhando o celular enquanto diz a frase."),
    ("Ho bisogno di più tempo.", "Eu preciso de mais tempo.", "Vocabulário: ho bisogno di = preciso de; più tempo = mais tempo.\nGramática: a expressão fixa é avere bisogno di, literalmente ter necessidade de.\nTreino: use para pedir prazo sem soar brusco."),
    ("Questa domanda è difficile.", "Esta pergunta é difícil.", "Vocabulário: domanda = pergunta; difficile = difícil.\nGramática: è com acento significa é; sem acento, e significa e.\nTreino: compare Questa domanda è facile e Questa domanda è difficile."),
    ("La risposta è molto semplice.", "A resposta é muito simples.", "Vocabulário: risposta = resposta; molto = muito; semplice = simples.\nGramática: semplice serve para masculino e feminino no singular.\nTreino: use depois de explicar algo de forma curta."),
    ("Vado al mercato dopo pranzo.", "Vou ao mercado depois do almoço.", "Vocabulário: vado = vou; mercato = mercado; dopo pranzo = depois do almoço.\nGramática: al = a + il, usado antes de mercato.\nTreino: troque mercato por lavoro, cinema ou parco."),
    ("Torno a casa verso le sette.", "Volto para casa por volta das sete.", "Vocabulário: torno = volto; verso = por volta de; le sette = sete horas.\nGramática: verso antes de horário indica aproximação.\nTreino: diga um horário real da sua rotina."),
    ("Oggi fa molto caldo.", "Hoje faz muito calor.", "Vocabulário: fa caldo = faz calor; molto = muito.\nGramática: para clima, italiano usa fare: fa caldo, fa freddo.\nTreino: contraste com Ho caldo, que é sensação pessoal."),
    ("Ho freddo in questa stanza.", "Estou com frio nesta sala.", "Vocabulário: ho freddo = estou com frio; stanza = sala/quarto.\nGramática: sensação física usa avere: ho freddo.\nTreino: não diga sono freddo para falar de sensação."),
    ("La porta è aperta.", "A porta está aberta.", "Vocabulário: porta = porta; aperta = aberta.\nGramática: aperta concorda com porta, feminino singular.\nTreino: troque aperta por chiusa para criar a frase oposta."),
    ("Il telefono non funziona bene.", "O telefone não funciona bem.", "Vocabulário: telefono = telefone; funziona = funciona; bene = bem.\nGramática: non nega o verbo funziona.\nTreino: use para explicar um problema simples."),
    ("Devo comprare una nuova penna.", "Preciso comprar uma caneta nova.", "Vocabulário: devo = devo/preciso; comprare = comprar; penna = caneta.\nGramática: dovere + infinitivo expressa necessidade.\nTreino: substitua penna por borsa, camicia ou bottiglia."),
    ("Cerco le chiavi nella borsa.", "Procuro as chaves na bolsa.", "Vocabulário: cerco = procuro; chiavi = chaves; borsa = bolsa.\nGramática: nella = in + la, usado com borsa.\nTreino: visualize a ação de procurar as chaves."),
    ("Leggo un libro prima di dormire.", "Leio um livro antes de dormir.", "Vocabulário: leggo = leio; prima di = antes de; dormire = dormir.\nGramática: prima di vem antes do infinitivo.\nTreino: troque leggere por studiare ou mangiare."),
    ("Scrivo una nota sul quaderno.", "Escrevo uma nota no caderno.", "Vocabulário: scrivo = escrevo; nota = anotação; quaderno = caderno.\nGramática: sul = su + il, sobre/no caderno.\nTreino: use quando estiver anotando uma frase nova."),
    ("La lezione comincia alle otto.", "A aula começa às oito.", "Vocabulário: lezione = aula; comincia = começa; alle otto = às oito.\nGramática: alle é usado com horas no plural.\nTreino: substitua otto pelo horário da sua aula."),
    ("Finisco il lavoro più tardi.", "Termino o trabalho mais tarde.", "Vocabulário: finisco = termino; lavoro = trabalho; più tardi = mais tarde.\nGramática: finire vira finisco na primeira pessoa.\nTreino: use para falar de agenda ou prazo."),
    ("Preferisco mangiare a casa.", "Prefiro comer em casa.", "Vocabulário: preferisco = prefiro; mangiare = comer; a casa = em casa.\nGramática: preferire vira preferisco na primeira pessoa.\nTreino: compare com Preferisco mangiare fuori."),
    ("Bevo acqua durante la giornata.", "Bebo água durante o dia.", "Vocabulário: bevo = bebo; acqua = água; durante = durante.\nGramática: durante la giornata indica ao longo do dia.\nTreino: repita pensando em um hábito saudável."),
    ("Cammino nel parco la sera.", "Caminho no parque à noite.", "Vocabulário: cammino = caminho; parco = parque; la sera = à noite.\nGramática: nel = in + il.\nTreino: troque parco por centro ou quartiere."),
    ("Guardo un film con mia sorella.", "Assisto a um filme com minha irmã.", "Vocabulário: guardo = vejo/assisto; film = filme; sorella = irmã.\nGramática: mia concorda com sorella.\nTreino: substitua sorella por fratello, madre ou amico."),
    ("Aiuto mio padre in cucina.", "Ajudo meu pai na cozinha.", "Vocabulário: aiuto = ajudo; padre = pai; cucina = cozinha.\nGramática: mio concorda com padre, masculino singular.\nTreino: use com pessoas da família para fixar possessivos."),
    ("Voglio imparare una parola nuova.", "Quero aprender uma palavra nova.", "Vocabulário: voglio = quero; imparare = aprender; parola nuova = palavra nova.\nGramática: voglio + infinitivo expressa intenção.\nTreino: fale antes de revelar a resposta de um card."),
    ("Ripeto la frase ad alta voce.", "Repito a frase em voz alta.", "Vocabulário: ripeto = repito; ad alta voce = em voz alta.\nGramática: ad alta voce é expressão fixa.\nTreino: faça exatamente isso antes de avaliar o card."),
    ("Non ricordo il suo nome.", "Não lembro o nome dele/dela.", "Vocabulário: ricordo = lembro; suo nome = nome dele/dela.\nGramática: suo concorda com nome, não necessariamente com a pessoa.\nTreino: use quando esquecer um nome em conversa."),
    ("Ricordo bene questa parola.", "Lembro bem esta palavra.", "Vocabulário: ricordo = lembro; bene = bem; parola = palavra.\nGramática: questa concorda com parola, feminino singular.\nTreino: diga depois de acertar um card com facilidade."),
    ("Mi serve una mano.", "Eu preciso de uma ajuda.", "Vocabulário: mi serve = preciso/me serve; una mano = uma mão/ajuda.\nUso real: expressão natural para pedir ajuda.\nTreino: imagine pedindo ajuda para carregar algo."),
    ("Posso fare una domanda?", "Posso fazer uma pergunta?", "Vocabulário: posso = posso; fare = fazer; domanda = pergunta.\nGramática: posso + infinitivo cria pedido de permissão.\nTreino: use antes de interromper alguém educadamente."),
    ("Non ho capito l'ultima parte.", "Não entendi a última parte.", "Vocabulário: ho capito = entendi; ultima parte = última parte.\nGramática: passato prossimo com avere: ho capito.\nTreino: use quando entendeu só uma parte da explicação."),
    ("Puoi scriverlo nel messaggio?", "Você pode escrever isso na mensagem?", "Vocabulário: scriverlo = escrever isso; messaggio = mensagem.\nGramática: lo grudado ao infinitivo retoma o que deve ser escrito.\nTreino: use quando precisar ver a frase por escrito."),
    ("Ci vediamo dopo la riunione.", "A gente se vê depois da reunião.", "Vocabulário: ci vediamo = a gente se vê; riunione = reunião.\nGramática: dopo + nome indica depois de algo.\nTreino: troque riunione por lezione ou pranzo."),
    ("Arrivo tra dieci minuti.", "Chego em dez minutos.", "Vocabulário: tra = em/daqui a; dieci minuti = dez minutos.\nGramática: tra com tempo indica quanto falta.\nTreino: use como resposta rápida pelo celular."),
    ("La macchina è davanti a casa.", "O carro está em frente de casa.", "Vocabulário: macchina = carro; davanti a = em frente a.\nGramática: davanti a casa não precisa de artigo nesse uso comum.\nTreino: substitua macchina por autobus ou bici."),
    ("Il negozio chiude presto oggi.", "A loja fecha cedo hoje.", "Vocabulário: negozio = loja; chiude = fecha; presto = cedo.\nGramática: oggi no fim marca o tempo da ação.\nTreino: use para avisar alguém sobre horário."),
    ("La cena è quasi pronta.", "O jantar está quase pronto.", "Vocabulário: cena = jantar; quasi = quase; pronta = pronta.\nGramática: pronta concorda com cena, feminino singular.\nTreino: use em contexto de casa/cozinha."),
    ("Metto il telefono sul tavolo.", "Coloco o telefone sobre a mesa.", "Vocabulário: metto = coloco; sul tavolo = na/sobre a mesa.\nGramática: sul = su + il.\nTreino: faça o gesto enquanto fala para fixar."),
    ("Prendo una giacca leggera.", "Pego uma jaqueta leve.", "Vocabulário: prendo = pego; giacca = jaqueta; leggera = leve.\nGramática: leggera concorda com giacca.\nTreino: use antes de sair de casa."),
    ("Oggi mi sento meglio.", "Hoje me sinto melhor.", "Vocabulário: mi sento = me sinto; meglio = melhor.\nGramática: sentirsi é reflexivo; mi marca primeira pessoa.\nTreino: compare com Oggi mi sento stanco."),
    ("Mi sembra una buona idea.", "Parece-me uma boa ideia.", "Vocabulário: mi sembra = me parece; buona idea = boa ideia.\nGramática: buona concorda com idea.\nTreino: use para concordar de forma natural."),
    ("Non è una buona idea.", "Não é uma boa ideia.", "Vocabulário: non è = não é; buona idea = boa ideia.\nGramática: non antes de è nega a frase inteira.\nTreino: use para discordar sem explicar muito."),
    ("Parliamo dopo, va bene?", "Falamos depois, está bem?", "Vocabulário: parliamo = falamos; dopo = depois; va bene = está bem.\nUso real: frase útil para adiar uma conversa.\nTreino: fale como combinação entre duas pessoas."),
    ("Ho lasciato le chiavi a casa.", "Deixei as chaves em casa.", "Vocabulário: ho lasciato = deixei; chiavi = chaves; a casa = em casa.\nGramática: passato prossimo com avere.\nTreino: use para relatar um problema comum."),
    ("Mi sono svegliato presto.", "Eu acordei cedo.", "Vocabulário: mi sono svegliato = acordei; presto = cedo.\nGramática: svegliarsi usa essere no passato prossimo.\nTreino: para feminino, diga svegliata."),
    ("Questa frase mi aiuta molto.", "Esta frase me ajuda muito.", "Vocabulário: aiuta = ajuda; molto = muito.\nGramática: mi indica a mim; a frase é o sujeito.\nTreino: use quando encontrar uma frase útil para memorizar."),
]


def iter_random_short_cards(limit=None):
    cards = RANDOM_SHORT_CARDS if limit is None else RANDOM_SHORT_CARDS[:limit]
    for index, (text, translation, note) in enumerate(cards, start=1):
        yield {
            'deck_key': f'random-{index:04d}',
            'order': 20000 + index,
            'italian_text': text,
            'portuguese_text': translation,
            'study_note': note,
            'source_title': RANDOM_SHORT_SOURCE_TITLE,
            'chapter': RANDOM_SHORT_CHAPTER,
        }
