from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('cadastro/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('sair/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('estudar/', views.study, name='study'),
    path('revisoes/', views.due_reviews, name='due_reviews'),
    path('revisao/<int:state_id>/', views.review, name='review'),
    path('tecnologia/estudar/', views.tech_study, name='tech_study'),
    path('tecnologia/revisoes/', views.tech_due_reviews, name='tech_due_reviews'),
    path('tecnologia/revisao/<int:state_id>/', views.tech_review, name='tech_review'),
    path('frases-curtas/estudar/', views.random_short_study, name='random_short_study'),
    path('frases-curtas/revisoes/', views.random_short_due_reviews, name='random_short_due_reviews'),
    path('frases-curtas/revisao/<int:state_id>/', views.random_short_review, name='random_short_review'),
    path('termo/', views.term_home, name='term_home'),
    path('termo/preencher/', views.term_register, name='term_register'),
    path('termo/consultar/', views.term_consult, name='term_consult'),
    path('termo/<uuid:public_id>/', views.term_signature, name='term_signature'),
    path('termo/<uuid:public_id>/baixar/', views.term_download, name='term_download'),
    path('termo/sucesso/<uuid:public_id>/', views.term_success, name='term_success'),
    path('inscricao_van/', views.van_home, name='van_home'),
    path('inscricao_van/fazer/', views.van_register, name='van_register'),
    path('inscricao_van/consultar/', views.van_consult, name='van_consult'),
    path('inscricao_van/termo/<uuid:public_id>/', views.van_signature, name='van_signature'),
    path('inscricao_van/termo/<uuid:public_id>/baixar/', views.van_download_term, name='van_download_term'),
    path('inscricao_van/sucesso/<uuid:public_id>/', views.van_success, name='van_success'),
    path('inscricao_van/admin/', views.van_admin_login, name='van_admin_login'),
    path('inscricao_van/admin/escolher/', views.van_admin_choice, name='van_admin_choice'),
    path('inscricao_van/admin/dashboard/', views.van_admin_dashboard, name='van_admin_dashboard'),
    path(
        'inscricao_van/admin/vagas/',
        views.van_admin_update_capacity,
        name='van_admin_update_capacity',
    ),
    path('inscricao_van/admin/termos/', views.term_admin_dashboard, name='term_admin_dashboard'),
    path('inscricao_van/admin/sair/', views.van_admin_logout, name='van_admin_logout'),
    path('inscricao_van/admin/termo/<uuid:public_id>/', views.van_admin_download_signed, name='van_admin_download_signed'),
    path(
        'inscricao_van/admin/termo-imagem/<uuid:public_id>/',
        views.term_admin_download_signed,
        name='term_admin_download_signed',
    ),
    path(
        'inscricao_van/admin/termo/<uuid:public_id>/desaprovar/',
        views.van_admin_reject_signed,
        name='van_admin_reject_signed',
    ),
    path(
        'inscricao_van/admin/inscricao/<uuid:public_id>/excluir/',
        views.van_admin_delete_registration,
        name='van_admin_delete_registration',
    ),
    path(
        'inscricao_van/admin/termo-imagem/<uuid:public_id>/desaprovar/',
        views.term_admin_reject_signed,
        name='term_admin_reject_signed',
    ),
    path('inscricao_van/admin/termos.zip', views.van_admin_download_all, name='van_admin_download_all'),
    path('inscricao_van/admin/termos-imagem.zip', views.term_admin_download_all, name='term_admin_download_all'),
]
