# Generated by Django 5.2.12 on 2026-05-14 00:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(default='Le avventure di Alice nel paese delle meraviglie', max_length=180)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('italian_text', models.TextField()),
                ('study_note', models.TextField(blank=True)),
                ('chapter', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='nome completo')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='telefone WhatsApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.3)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_grade', models.CharField(blank=True, choices=[('again', 'Errei'), ('hard', 'Difícil'), ('good', 'Bom'), ('easy', 'Fácil')], max_length=12)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.studyphrase')),
            ],
            options={
                'ordering': ['due_at', 'phrase__order'],
                'unique_together': {('user', 'phrase')},
            },
        ),
    ]
