# Generated by Django 5.2.12 on 2026-05-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyphrase',
            name='portuguese_text',
            field=models.TextField(blank=True),
        ),
    ]
