# Generated by Django 5.2.12 on 2026-05-14 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_studyphrase_portuguese_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstate',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
