# Generated by Django 5.2.12 on 2026-05-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_reviewstate_first_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyphrase',
            name='deck_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
    ]
