# Generated by Django 5.2.12 on 2026-05-21 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_studyphrase_deck_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('responsible_name', models.CharField(max_length=180, verbose_name='nome do responsavel')),
                ('responsible_rg', models.CharField(max_length=40, verbose_name='RG do responsavel')),
                ('responsible_cpf', models.CharField(db_index=True, max_length=20, verbose_name='CPF do responsavel')),
                ('responsible_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone/WhatsApp')),
                ('responsible_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('minor_name', models.CharField(max_length=180, verbose_name='nome do menor')),
                ('minor_birth_date', models.DateField(db_index=True, verbose_name='data de nascimento do menor')),
                ('minor_document', models.CharField(blank=True, max_length=60, verbose_name='RG/CPF do menor')),
                ('transport_by', models.CharField(default='van', max_length=120, verbose_name='transporte realizado por')),
                ('signed_term', models.FileField(blank=True, upload_to='inscricao_van/termos_assinados/', verbose_name='termo assinado')),
                ('status', models.CharField(choices=[('pending_signature', 'Falta enviar termo assinado'), ('signed_received', 'Inscricao da van feita')], db_index=True, default='pending_signature', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
