# Generated by Django 5.2.12 on 2026-05-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_vanregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanregistration',
            name='responsible_cpf',
            field=models.CharField(db_index=True, max_length=20, verbose_name='CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='vanregistration',
            name='responsible_name',
            field=models.CharField(max_length=180, verbose_name='nome do responsável'),
        ),
        migrations.AlterField(
            model_name='vanregistration',
            name='responsible_rg',
            field=models.CharField(max_length=40, verbose_name='RG do responsável'),
        ),
        migrations.AlterField(
            model_name='vanregistration',
            name='status',
            field=models.CharField(choices=[('pending_signature', 'Falta enviar termo assinado'), ('signed_received', 'Inscrição da van feita')], db_index=True, default='pending_signature', max_length=32),
        ),
    ]
