# Generated by Django 5.2.12 on 2026-05-21 01:29

import studies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_vanregistration_responsible_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanregistration',
            name='signed_term',
            field=models.FileField(blank=True, upload_to=studies.models.van_signed_term_upload_path, verbose_name='termo assinado'),
        ),
    ]
