# Generated by Django 5.2.12 on 2026-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_alter_vanregistration_signed_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanregistration',
            name='city',
            field=models.CharField(blank=True, default='São Carlos', max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data final do evento'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='event_name',
            field=models.CharField(default='Passaporte: Sua Identidade em Alta Definição', max_length=180, verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='event_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='data inicial do evento'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='health_info',
            field=models.TextField(blank=True, default='', verbose_name='informações importantes de saúde'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='minor_cpf',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='CPF do adolescente'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='responsible_phone_alt',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='telefone alternativo'),
        ),
        migrations.AddField(
            model_name='vanregistration',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='data do termo'),
        ),
        migrations.AlterField(
            model_name='vanregistration',
            name='minor_birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='data de nascimento do menor'),
        ),
        migrations.AlterField(
            model_name='vanregistration',
            name='responsible_rg',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='RG do responsável'),
        ),
    ]
