# Generated by Django 5.2.12 on 2026-05-22 02:13

import studies.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_vanregistration_city_vanregistration_event_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('responsible_name', models.CharField(max_length=180, verbose_name='nome do responsável')),
                ('responsible_cpf', models.CharField(db_index=True, max_length=20, verbose_name='CPF do responsável')),
                ('minor_name', models.CharField(max_length=180, verbose_name='nome do adolescente')),
                ('minor_cpf', models.CharField(db_index=True, max_length=20, verbose_name='CPF do adolescente')),
                ('event_name', models.CharField(max_length=180, verbose_name='evento')),
                ('event_start_date', models.DateField(verbose_name='data inicial do evento')),
                ('event_end_date', models.DateField(verbose_name='data final do evento')),
                ('health_info', models.TextField(blank=True, default='', verbose_name='informações importantes de saúde')),
                ('responsible_phone', models.CharField(max_length=30, verbose_name='telefone do responsável')),
                ('responsible_phone_alt', models.CharField(blank=True, default='', max_length=30, verbose_name='segundo telefone do responsável')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('signature_date', models.DateField(verbose_name='data do termo')),
                ('signed_term', models.FileField(blank=True, upload_to=studies.models.image_authorization_signed_upload_path, verbose_name='termo assinado')),
                ('status', models.CharField(choices=[('pending_signature', 'Falta enviar termo assinado'), ('signed_received', 'Termo assinado recebido')], db_index=True, default='pending_signature', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
