# Generated by Django 5.2.12 on 2026-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_imageauthorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=17, verbose_name='quantidade de vagas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao da van',
                'verbose_name_plural': 'configuracoes da van',
            },
        ),
    ]
