# Generated by Django 5.2.12 on 2026-05-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_vansettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanregistration',
            name='signed_term_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='responsavel avisado sobre termo'),
        ),
    ]
